// backend/src/services/excel/export-map.ts
import * as noteConfigs from "./note-configs";

export const NOTE_EXPORT_MAP: Record<
    string,
    { config: any; sheetName: string }
> = {
    "1": { config: noteConfigs.CONFIG_NOTE1, sheetName: "Note 1 " },
    "2": { config: noteConfigs.CONFIG_NOTE2, sheetName: "NOTE 2" },
    "3A": { config: noteConfigs.CONFIG_NOTE3A, sheetName: "NOTE 3A" },
    "3B": { config: noteConfigs.CONFIG_NOTE3B, sheetName: "NOTE 3B" },
    "3C": { config: noteConfigs.CONFIG_NOTE3C, sheetName: "NOTE 3C" },
    "3C_C01": { config: noteConfigs.CONFIG_C01_NOTE3C, sheetName: "C01-NOTE 3C" },
    "3D": { config: noteConfigs.CONFIG_NOTE3D, sheetName: "NOTE 3D" },
    "3E": { config: noteConfigs.CONFIG_NOTE3E, sheetName: "NOTE 3E" },
    "3F": { config: noteConfigs.CONFIG_NOTE3F, sheetName: "NOTE 3F" },
    "4": { config: noteConfigs.CONFIG_NOTE4, sheetName: "NOTE 4" },
    "5": { config: noteConfigs.CONFIG_NOTE5, sheetName: "NOTE 5 " },
    "6": { config: noteConfigs.CONFIG_NOTE6, sheetName: "NOTE 6 " },
    "7": { config: noteConfigs.CONFIG_NOTE7, sheetName: "NOTE 7 " },
    "8": { config: noteConfigs.CONFIG_NOTE8, sheetName: "NOTE 8 " },
    "9": { config: noteConfigs.CONFIG_NOTE9, sheetName: "NOTE 9" },
    "10": { config: noteConfigs.CONFIG_NOTE10, sheetName: "NOTE 10" },
    "11": { config: noteConfigs.CONFIG_NOTE11, sheetName: "NOTE 11" },
    "12": { config: noteConfigs.CONFIG_NOTE12, sheetName: "NOTE 12" },
    "13": { config: noteConfigs.CONFIG_NOTE13, sheetName: "NOTE 13" },
    "14": { config: noteConfigs.CONFIG_NOTE14, sheetName: "NOTE 14" },
    "15A": { config: noteConfigs.CONFIG_NOTE15A, sheetName: "NOTE 15A" },
    "15B": { config: noteConfigs.CONFIG_NOTE15B, sheetName: "NOTE 15B" },
    "16A": { config: noteConfigs.CONFIG_NOTE16A, sheetName: "NOTE 16A " },
    "16B": { config: noteConfigs.CONFIG_NOTE16B, sheetName: "NOTE 16B" },
    "16B bis": { config: noteConfigs.CONFIG_NOTE16B_BIS, sheetName: "NOTE 16B BIS" },
    "16C": { config: noteConfigs.CONFIG_NOTE16C, sheetName: "NOTE 16C" },
    "17": { config: noteConfigs.CONFIG_NOTE17, sheetName: "NOTE 17" },
    "C1/17": { config: noteConfigs.CONFIG_NOTE17_C1, sheetName: "C1-NOTE 17" },
    "18": { config: noteConfigs.CONFIG_NOTE18, sheetName: "NOTE 18" },
    "19": { config: noteConfigs.CONFIG_NOTE19, sheetName: "NOTE 19" },
    "20": { config: noteConfigs.CONFIG_NOTE20, sheetName: "NOTE 20" },
    "21": { config: noteConfigs.CONFIG_NOTE21, sheetName: "NOTE 21" },
    "22": { config: noteConfigs.CONFIG_NOTE22, sheetName: "NOTE 22" },
    "23": { config: noteConfigs.CONFIG_NOTE23, sheetName: "NOTE 23" },
    "24": { config: noteConfigs.CONFIG_NOTE24, sheetName: "NOTE 24" },
    "25": { config: noteConfigs.CONFIG_NOTE25, sheetName: "NOTE 25" },
    "C1/25": { config: noteConfigs.CONFIG_NOTE25_C1, sheetName: "C1-NOTE 25" },
    "C2/25": { config: noteConfigs.CONFIG_NOTE25_C2, sheetName: "C2-NOTE 25" },
    "26": { config: noteConfigs.CONFIG_NOTE26, sheetName: "NOTE 26" },
    "28": { config: noteConfigs.CONFIG_NOTE28, sheetName: "NOTE 28" },
    "C1/28": { config: noteConfigs.CONFIG_NOTE28_C1, sheetName: "C1-NOTE 28" },
    "C2/28": { config: noteConfigs.CONFIG_NOTE28_C2, sheetName: "C2-NOTE 28" },
    "29": { config: noteConfigs.CONFIG_NOTE29, sheetName: "NOTE 29" },
    "30": { config: noteConfigs.CONFIG_NOTE30, sheetName: "NOTE 30" },
    "31": { config: noteConfigs.CONFIG_NOTE31, sheetName: "NOTE 31" },
    "32": { config: noteConfigs.CONFIG_NOTE32, sheetName: "NOTE 32" },
    "33": { config: noteConfigs.CONFIG_NOTE33, sheetName: "NOTE 33" },
    "34": { config: noteConfigs.CONFIG_NOTE34, sheetName: "NOTE 34" },
};
