import React from "react";
import {
  FileText,
  Building,
  CreditCard,
  Calculator,
  BarChart,
  FileSpreadsheet,
  Users,
  TrendingUp,
  ShoppingCart,
  Grid3X3,
  List,
  Monitor,
} from "lucide-react";

// Import all note components
import {
  Note1,
  Note2,
  Note3A,
  Note3B,
  Note3C,
  Note3D,
  Note3E,
  Note3F,
  Note4,
  Note5,
  Note6,
  Note7,
  Note8,
  Note9,
  Note10,
  Note11,
  Note12,
  Note13,
  Note14,
  Note15A,
  Note15B,
  Note16A,
  Note16B,
  Note16Bbis,
  Note16C,
  Note17,
  Note18,
  Note19,
  Note20,
  Note21,
  Note22,
  Note23,
  Note24,
  Note25,
  Note26,
  Note27A,
  Note27B,
  Note28,
  Note29,
  Note30,
  Note31,
  Note32,
  Note33,
  Note34,
  FicheR3,
  C01Note3C,
  C1Note17,
  C1Note25,
  C1Note27A,
  C1Note28,
  C2Note25,
  C2Note28,
  CF1,
  CF1Bis,
  CF1Quater,
  CF1Ter,
  CF2,
  CF2Bis,
  CF2Ter,
  CompteResultat,
  GrilleAnalyseNotes,
  PageDeGarde,
  Sommaire,
  TableauFluxTresorerie,
  BilanPaysage,
  Impot21,
  Impot22,
  Fiche1,
  Fiche2,
  Fiche3,
  Fiche4,
  Fiche5,
  BilanActif,
  BilanPassif,
  Charges,
  CompteGeneralPertesProfits,
  EtatC4,
  EtatC11,
  EtatC11Vie,
  Produits,
  Ass1,
  Ass2,
  Ass3,
  Ass4,
  Ass5,
  Ass6,
  Ass7,
  Ass8,
  Ass9,
  Ass10,
  Ass11,
  DeclarationAnnuel,
  SommesVerse,
  TVA,
  Versements,
  Tableau30,
  Tableau31,
  Tableau32,
  Tableau33,
  Tableau34,
  Tableau35A,
  Tableau35B,
  Tableau36,
  Tableau37,
  Tableau38,
  Tableau39,
  Tableau40,
  Tableau41A,
  Tableau41B,
  Tableau42,
  Tableau43A,
  Tableau43B,
  Tableau44A,
  Annexe6,
  GrilleAnalyseNotesSMT,
  ModBilan,
  Note1Smt,
  Note2Smt,
  Note3Smt,
  Note4Smt,
  Note5Smt,
  Note6Smt,
  T1,
  T1Bis,
  T1Ter,
  T2,
  T3,
  T4,
  T5,
  T6,
  T7,
  T8,
  T9,
} from "../components/Notes";

export interface NoteItem {
  id: string;
  name: string;
  title: string;
  description: string;
  category: string;
  component: React.ComponentType;
  icon: React.ReactNode;
  reportType: "normal" | "smt" | "assurance";
}

export const NOTES_DATA: NoteItem[] = [
  // Normal Reports
  {
    id: "note-1",
    name: "Note 1",
    title: "Dettes Garanties",
    description:
      "Dettes financières et ressources assimilées garanties par des sûretés réelles",
    category: "Dettes",
    component: Note1,
    icon: <FileText className="h-6 w-6 text-blue-600" />,
    reportType: "normal" as const,
  },
  {
    id: "note-2",
    name: "Note 2",
    title: "Informations Obligatoires",
    description: "Déclaration de conformité au SYSCOHADA et règles comptables",
    category: "Informations",
    component: Note2,
    icon: <FileText className="h-6 w-6 text-green-600" />,
    reportType: "normal",
  },
  {
    id: "note-3a",
    name: "Note 3A",
    title: "Immobilisations Brutes",
    description: "Tableau des mouvements des immobilisations brutes",
    category: "Immobilisations",
    component: Note3A,
    icon: <Building className="h-6 w-6 text-purple-600" />,
    reportType: "normal",
  },
  {
    id: "note-3b",
    name: "Note 3B",
    title: "Biens Pris en Location Acquisition",
    description: "Immobilisations financees par credit-bail et contrats assimiles",
    category: "Immobilisations",
    component: Note3B,
    icon: <Building className="h-6 w-6 text-orange-600" />,
    reportType: "normal",
  },
  {
    id: "note-3c",
    name: "Note 3C",
    title: "Immobilisations : Amortissements",
    description: "Amortissements cumules des immobilisations",
    category: "Amortissements",
    component: Note3C,
    icon: <CreditCard className="h-6 w-6 text-red-600" />,
    reportType: "normal",
  },
  {
    id: "note-3d",
    name: "Note 3D",
    title: "Immobilisations : Plus et Moins Values de Cession",
    description: "Resultat des cessions d'immobilisations",
    category: "Immobilisations",
    component: Note3D,
    icon: <Calculator className="h-6 w-6 text-teal-600" />,
    reportType: "normal",
  },
  {
    id: "note-3e",
    name: "Note 3E",
    title: "Informations sur les Réévaluations",
    description: "Nature, méthode et traitement fiscal des réévaluations effectuées",
    category: "Immobilisations",
    component: Note3E,
    icon: <TrendingUp className="h-6 w-6 text-amber-600" />,
    reportType: "normal",
  },
  {
    id: "note-3f",
    name: "Note 3F",
    title: "Etalement des Charges Immobilisees",
    description: "Tableau d'etalement des charges immobilisees",
    category: "Immobilisations",
    component: Note3F,
    icon: <BarChart className="h-6 w-6 text-indigo-600" />,
    reportType: "normal",
  },
  {
    id: "note-4",
    name: "Note 4",
    title: "Immobilisations Financieres",
    description: "Titres de participation, prets et autres immobilisations financieres",
    category: "Immobilisations",
    component: Note4,
    icon: <FileSpreadsheet className="h-6 w-6 text-yellow-600" />,
    reportType: "normal",
  },
  {
    id: "note-5",
    name: "Note 5",
    title: "Actif et Passif Circulant HAO",
    description: "Creances et dettes hors activites ordinaires",
    category: "Creances",
    component: Note5,
    icon: <Users className="h-6 w-6 text-cyan-600" />,
    reportType: "normal",
  },
  {
    id: "note-6",
    name: "Note 6",
    title: "Stocks et En-cours",
    description: "Stocks de marchandises, matieres et en-cours",
    category: "Stocks",
    component: Note6,
    icon: <CreditCard className="h-6 w-6 text-emerald-600" />,
    reportType: "normal",
  },
  {
    id: "note-7",
    name: "Note 7",
    title: "Clients",
    description: "Creances clients et comptes rattaches",
    category: "Creances",
    component: Note7,
    icon: <BarChart className="h-6 w-6 text-pink-600" />,
    reportType: "normal",
  },
  {
    id: "note-8",
    name: "Note 8",
    title: "Autres Creances",
    description: "Personnel, Etat, associes et debiteurs divers",
    category: "Creances",
    component: Note8,
    icon: <FileText className="h-6 w-6 text-gray-600" />,
    reportType: "normal",
  },
  {
    id: "note-9",
    name: "Note 9",
    title: "Titres de Placement",
    description: "Titres de trésor et autres valeurs mobilières de placement",
    category: "Titres",
    component: Note9,
    icon: <CreditCard className="h-6 w-6 text-purple-600" />,
    reportType: "normal",
  },
  {
    id: "note-10",
    name: "Note 10",
    title: "Valeurs à Encaisser",
    description: "Effets à encaisser et autres valeurs à l'encaissement",
    category: "Valeurs",
    component: Note10,
    icon: <FileSpreadsheet className="h-6 w-6 text-cyan-600" />,
    reportType: "normal",
  },
  {
    id: "note-11",
    name: "Note 11",
    title: "Disponibilités",
    description: "Disponibilités et équivalents de trésorerie",
    category: "Trésorerie",
    component: Note11,
    icon: <CreditCard className="h-6 w-6 text-emerald-600" />,
    reportType: "normal",
  },
  {
    id: "note-12",
    name: "Note 12",
    title: "Ecarts de Conversion & Transferts",
    description: "Écarts de conversion et transferts de charges",
    category: "Comptes",
    component: Note12,
    icon: <Calculator className="h-6 w-6 text-purple-600" />,
    reportType: "normal",
  },
  {
    id: "note-13",
    name: "Note 13",
    title: "Capital Social",
    description: "Valeur nominale des actions ou parts sociales",
    category: "Capitaux Propres",
    component: Note13,
    icon: <Building className="h-6 w-6 text-amber-600" />,
    reportType: "normal",
  },
  {
    id: "note-14",
    name: "Note 14",
    title: "Primes et Réserves",
    description: "Primes d'émission et réserves diverses",
    category: "Capitaux",
    component: Note14,
    icon: <BarChart className="h-6 w-6 text-teal-600" />,
    reportType: "normal",
  },
  {
    id: "note-15a",
    name: "Note 15A",
    title: "Subventions et Provisions Réglementées",
    description: "Total subventions et provisions réglementées",
    category: "Comptes",
    component: Note15A,
    icon: <Calculator className="h-6 w-6 text-purple-600" />,
    reportType: "normal",
  },
  {
    id: "note-15b",
    name: "Note 15B",
    title: "Autres Fonds Propres",
    description: "Autres fonds propres et capitaux assimilés",
    category: "Capitaux",
    component: Note15B,
    icon: <BarChart className="h-6 w-6 text-amber-600" />,
    reportType: "normal",
  },
  {
    id: "note-16a",
    name: "Note 16A",
    title: "Dettes Financieres et Ressources Assimilees",
    description: "Emprunts, dettes de location-acquisition et provisions pour risques",
    category: "Dettes",
    component: Note16A,
    icon: <Calculator className="h-6 w-6 text-indigo-600" />,
    reportType: "normal",
  },
  {
    id: "note-16b",
    name: "Note 16B",
    title: "Engagements de Retraite (Methode Actuarielle)",
    description: "Engagements de retraite et avantages assimiles evalues par methode actuarielle",
    category: "Dettes",
    component: Note16B,
    icon: <Calculator className="h-6 w-6 text-cyan-600" />,
    reportType: "normal",
  },
  {
    id: "note-16bbis",
    name: "Note 16B bis",
    title: "Engagements de Retraite et Avantages Assimiles",
    description: "Actifs et passifs du regime de retraite",
    category: "Dettes",
    component: Note16Bbis,
    icon: <Calculator className="h-6 w-6 text-emerald-600" />,
    reportType: "normal",
  },
  {
    id: "note-16c",
    name: "Note 16C",
    title: "Actifs et Passifs Eventuels",
    description: "Engagements hors bilan, cautions et garanties",
    category: "Dettes",
    component: Note16C,
    icon: <Calculator className="h-6 w-6 text-pink-600" />,
    reportType: "normal",
  },
  {
    id: "note-17",
    name: "Note 17",
    title: "Fournisseurs d'Exploitation",
    description: "Fournisseurs et comptes rattachés d'exploitation",
    category: "Tiers",
    component: Note17,
    icon: <Users className="h-6 w-6 text-orange-600" />,
    reportType: "normal",
  },
  {
    id: "note-18",
    name: "Note 18",
    title: "Dettes Fiscales et Sociales",
    description: "Dettes fiscales et sociales envers l'État et organismes",
    category: "Dettes",
    component: Note18,
    icon: <FileText className="h-6 w-6 text-red-600" />,
    reportType: "normal",
  },
  {
    id: "note-19",
    name: "Note 19",
    title: "Autres Dettes",
    description: "Autres dettes et provisions pour risques à court terme",
    category: "Dettes",
    component: Note19,
    icon: <FileText className="h-6 w-6 text-orange-600" />,
    reportType: "normal",
  },
  {
    id: "note-20",
    name: "Note 20",
    title: "Banques et Crédits",
    description: "Banques, crédits d'escompte et de trésorerie",
    category: "Financement",
    component: Note20,
    icon: <CreditCard className="h-6 w-6 text-emerald-600" />,
    reportType: "normal",
  },
  {
    id: "note-21",
    name: "Note 21",
    title: "Chiffre d'Affaires",
    description: "Chiffre d'affaires et autres produits d'exploitation",
    category: "Revenus",
    component: Note21,
    icon: <TrendingUp className="h-6 w-6 text-green-600" />,
    reportType: "normal",
  },
  {
    id: "note-22",
    name: "Note 22",
    title: "Achats",
    description: "Achats de marchandises, matières premières et autres achats",
    category: "Achats",
    component: Note22,
    icon: <ShoppingCart className="h-6 w-6 text-blue-600" />,
    reportType: "normal",
  },
  {
    id: "note-23",
    name: "Note 23",
    title: "Transports",
    description: "Frais de transports et déplacements",
    category: "Transports",
    component: Note23,
    icon: <TrendingUp className="h-6 w-6 text-orange-600" />,
    reportType: "normal",
  },
  {
    id: "note-24",
    name: "Note 24",
    title: "Services Extérieurs",
    description: "Prestations de services, travaux et études",
    category: "Services",
    component: Note24,
    icon: <Users className="h-6 w-6 text-cyan-600" />,
    reportType: "normal",
  },
  {
    id: "note-25",
    name: "Note 25",
    title: "Impots et Taxes",
    description: "Impots et taxes directs, indirects et droits d'enregistrement",
    category: "Charges",
    component: Note25,
    icon: <Calculator className="h-6 w-6 text-orange-600" />,
    reportType: "normal",
  },
  {
    id: "note-26",
    name: "Note 26",
    title: "Autres Charges",
    description: "Autres charges diverses et exceptionnelles",
    category: "Charges",
    component: Note26,
    icon: <Calculator className="h-6 w-6 text-gray-600" />,
    reportType: "normal",
  },
  {
    id: "note-27a",
    name: "Note 27A",
    title: "Charges de Personnel",
    description: "Rémunérations, charges sociales et avantages du personnel",
    category: "Personnel",
    component: Note27A,
    icon: <Users className="h-6 w-6 text-indigo-600" />,
    reportType: "normal",
  },
  {
    id: "note-27b",
    name: "Note 27B",
    title: "Effectifs et Masse Salariale",
    description: "Effectifs du personnel et masse salariale par catégorie",
    category: "Personnel",
    component: Note27B,
    icon: <Users className="h-6 w-6 text-purple-600" />,
    reportType: "normal",
  },
  {
    id: "note-28",
    name: "Note 28",
    title: "Provisions et Dépréciations",
    description: "Provisions et dépréciations inscrites au bilan",
    category: "Provisions",
    component: Note28,
    icon: <Calculator className="h-6 w-6 text-red-600" />,
    reportType: "normal",
  },
  {
    id: "note-29",
    name: "Note 29",
    title: "Charges et Revenus Financiers",
    description: "Charges et revenus financiers de l'exercice",
    category: "Financier",
    component: Note29,
    icon: <CreditCard className="h-6 w-6 text-emerald-600" />,
    reportType: "normal",
  },
  {
    id: "note-30",
    name: "Note 30",
    title: "Autres Charges et Produits HAO",
    description: "Autres charges et produits hors activités ordinaires",
    category: "Résultats",
    component: Note30,
    icon: <BarChart className="h-6 w-6 text-gray-600" />,
    reportType: "normal",
  },
  {
    id: "note-31",
    name: "Note 31",
    title: "Répartition du Résultat",
    description:
      "Répartition du résultat et éléments caractéristiques des 5 derniers exercices",
    category: "Résultats",
    component: Note31,
    icon: <BarChart className="h-6 w-6 text-amber-600" />,
    reportType: "normal",
  },
  {
    id: "note-32",
    name: "Note 32",
    title: "Production de l'Exercice",
    description: "État de la production de l'exercice avec ventes et stocks",
    category: "Production",
    component: Note32,
    icon: <FileSpreadsheet className="h-6 w-6 text-yellow-600" />,
    reportType: "normal",
  },
  {
    id: "note-33",
    name: "Note 33",
    title: "Achats Destinés à la Production",
    description: "Achats de matières et produits destinés à la production",
    category: "Achats",
    component: Note33,
    icon: <ShoppingCart className="h-6 w-6 text-blue-600" />,
    reportType: "normal",
  },
  {
    id: "note-34",
    name: "Note 34",
    title: "Fiche de Synthese des Indicateurs Financiers",
    description: "Soldes intermediaires de gestion, CAFG et structure financiere",
    category: "Synthese",
    component: Note34,
    icon: <FileText className="h-6 w-6 text-purple-600" />,
    reportType: "normal",
  },
  {
    id: "fiche-r3",
    name: "Fiche R3",
    title: "Dirigeants & Conseil d'Administration",
    description: "Fiche d'identification des dirigeants et membres du conseil",
    category: "Dirigeants",
    component: FicheR3,
    icon: <Users className="h-6 w-6 text-indigo-600" />,
    reportType: "normal",
  },
  {
    id: "fiche-1",
    name: "Fiche 1",
    title: "Fiche d'Identification",
    description: "Fiche d'identification de l'entreprise",
    category: "Identification",
    component: Fiche1,
    icon: <FileText className="h-6 w-6 text-purple-600" />,
    reportType: "normal",
  },
  {
    id: "fiche-2",
    name: "Fiche 2",
    title: "Fiche de Renseignement",
    description: "Fiche de renseignement sur l'activité de l'entreprise",
    category: "Identification",
    component: Fiche2,
    icon: <FileText className="h-6 w-6 text-indigo-600" />,
    reportType: "normal",
  },
  {
    id: "fiche-3",
    name: "Fiche 3",
    title: "Fiche d'Information Complémentaire",
    description: "Fiche d'information complémentaire sur l'activité",
    category: "Identification",
    component: Fiche3,
    icon: <FileText className="h-6 w-6 text-teal-600" />,
    reportType: "normal",
  },
  {
    id: "fiche-4",
    name: "Fiche 4",
    title: "Fiche de Suivi",
    description: "Fiche de suivi et de contrôle des informations",
    category: "Suivi",
    component: Fiche4,
    icon: <FileText className="h-6 w-6 text-orange-600" />,
    reportType: "normal",
  },
  {
    id: "fiche-5",
    name: "Fiche 5",
    title: "Fiche de Synthèse",
    description: "Fiche de synthèse des informations clés",
    category: "Synthèse",
    component: Fiche5,
    icon: <FileText className="h-6 w-6 text-pink-600" />,
    reportType: "normal",
  },
  {
    id: "c01-note3c",
    name: "C01 Note 3C",
    title: "Amortissements Différés",
    description:
      "Tableau de suivi des amortissements déductibles réputés différés en période déficitaire",
    category: "Fiscal",
    component: C01Note3C,
    icon: <Calculator className="h-6 w-6 text-red-600" />,
    reportType: "normal",
  },
  {
    id: "c1-note17",
    name: "C1 Note 17",
    title: "Fournisseurs d'Exploitation - C1",
    description: "Fournisseurs d'exploitation - catégorie C1",
    category: "Tiers",
    component: C1Note17,
    icon: <Users className="h-6 w-6 text-cyan-600" />,
    reportType: "normal",
  },
  {
    id: "c1-note25",
    name: "C1 Note 25",
    title: "Autres Charges - C1",
    description: "Autres charges d'exploitation - catégorie C1",
    category: "Charges",
    component: C1Note25,
    icon: <Calculator className="h-6 w-6 text-red-600" />,
    reportType: "normal",
  },
  {
    id: "c1-note27a",
    name: "C1 Note 27A",
    title: "Charges de Personnel - C1",
    description: "Rémunérations et charges sociales - catégorie C1",
    category: "Personnel",
    component: C1Note27A,
    icon: <Users className="h-6 w-6 text-indigo-600" />,
    reportType: "normal",
  },
  {
    id: "c1-note28",
    name: "C1 Note 28",
    title: "Provisions et Dépréciations - C1",
    description: "Provisions et dépréciations - catégorie C1",
    category: "Provisions",
    component: C1Note28,
    icon: <Calculator className="h-6 w-6 text-teal-600" />,
    reportType: "normal",
  },
  {
    id: "c2-note25",
    name: "C2 Note 25",
    title: "Autres Charges - C2",
    description: "Autres charges d'exploitation - catégorie C2",
    category: "Charges",
    component: C2Note25,
    icon: <Calculator className="h-6 w-6 text-orange-600" />,
    reportType: "normal",
  },
  {
    id: "c2-note28",
    name: "C2 Note 28",
    title: "Provisions et Dépréciations - C2",
    description: "Provisions et dépréciations - catégorie C2",
    category: "Provisions",
    component: C2Note28,
    icon: <Calculator className="h-6 w-6 text-pink-600" />,
    reportType: "normal",
  },
  {
    id: "cf1",
    name: "CF1",
    title: "Passage Résultat Comptable Fiscal",
    description: "Tableau de passage du résultat comptable au résultat fiscal",
    category: "Fiscal",
    component: CF1,
    icon: <Calculator className="h-6 w-6 text-red-600" />,
    reportType: "normal",
  },
  {
    id: "cf1-bis",
    name: "CF1 Bis",
    title: "Passage Résultat Comptable Fiscal - Bis",
    description: "Tableau de passage résultat comptable fiscal - version bis",
    category: "Fiscal",
    component: CF1Bis,
    icon: <Calculator className="h-6 w-6 text-blue-600" />,
    reportType: "normal",
  },
  {
    id: "cf1-ter",
    name: "CF1 Ter",
    title: "Passage Résultat Comptable Fiscal - Ter",
    description: "Tableau de passage résultat comptable fiscal - version ter",
    category: "Fiscal",
    component: CF1Ter,
    icon: <Calculator className="h-6 w-6 text-purple-600" />,
    reportType: "normal",
  },
  {
    id: "cf1-quater",
    name: "CF1 Quater",
    title: "Passage Résultat Comptable Fiscal - Quater",
    description:
      "Tableau de passage résultat comptable fiscal - version quater",
    category: "Fiscal",
    component: CF1Quater,
    icon: <Calculator className="h-6 w-6 text-green-600" />,
    reportType: "normal",
  },
  {
    id: "cf2",
    name: "CF2",
    title: "Tableau des Impôts sur les Sociétés",
    description: "Tableau de détermination des impôts sur les sociétés",
    category: "Fiscal",
    component: CF2,
    icon: <Calculator className="h-6 w-6 text-red-600" />,
    reportType: "normal",
  },
  {
    id: "cf2-bis",
    name: "CF2 Bis",
    title: "Tableau des Impôts - Bis",
    description: "Tableau de détermination des impôts - version bis",
    category: "Fiscal",
    component: CF2Bis,
    icon: <Calculator className="h-6 w-6 text-orange-600" />,
    reportType: "normal",
  },
  {
    id: "cf2-ter",
    name: "CF2 Ter",
    title: "Tableau des Impôts - Ter",
    description: "Tableau de détermination des impôts - version ter",
    category: "Fiscal",
    component: CF2Ter,
    icon: <Calculator className="h-6 w-6 text-cyan-600" />,
    reportType: "normal",
  },
  {
    id: "impot-21",
    name: "Impot 21",
    title: "Tableau Passage Résultat Comptable Fiscal",
    description:
      "Tableau de passage du résultat comptable avant impôt au résultat fiscal",
    category: "Fiscal",
    component: Impot21,
    icon: <Calculator className="h-6 w-6 text-blue-600" />,
    reportType: "normal",
  },
  {
    id: "impot-22",
    name: "Impot 22",
    title: "Tableau Détermination Impôt Résultat",
    description: "Tableau de détermination de l'impôt sur le résultat",
    category: "Fiscal",
    component: Impot22,
    icon: <Calculator className="h-6 w-6 text-green-600" />,
    reportType: "normal",
  },
  {
    id: "compte-resultat",
    name: "Compte de Résultat",
    title: "État des Résultats",
    description: "État des résultats de l'exercice",
    category: "États",
    component: CompteResultat,
    icon: <BarChart className="h-6 w-6 text-emerald-600" />,
    reportType: "normal",
  },
  {
    id: "grille-analyse-notes",
    name: "Grille d'Analyse des Notes",
    title: "Analyse Structurée des Notes",
    description: "Grille d'analyse et de vérification des notes comptables",
    category: "Analyse",
    component: GrilleAnalyseNotes,
    icon: <Grid3X3 className="h-6 w-6 text-indigo-600" />,
    reportType: "normal",
  },
  {
    id: "page-garde",
    name: "Page de Garde",
    title: "Couverture du Rapport",
    description: "Page de garde et informations générales du rapport",
    category: "Présentation",
    component: PageDeGarde,
    icon: <FileText className="h-6 w-6 text-gray-600" />,
    reportType: "normal",
  },
  {
    id: "sommaire",
    name: "Sommaire",
    title: "Table des Matières",
    description: "Sommaire et organisation du rapport DSF",
    category: "Navigation",
    component: Sommaire,
    icon: <List className="h-6 w-6 text-blue-600" />,
    reportType: "normal",
  },
  {
    id: "tableau-flux-tresorerie",
    name: "Tableau des Flux de Trésorerie",
    title: "Flux de Trésorerie",
    description: "Tableau des flux de trésorerie de l'exercice",
    category: "Trésorerie",
    component: TableauFluxTresorerie,
    icon: <TrendingUp className="h-6 w-6 text-green-600" />,
    reportType: "normal",
  },
  {
    id: "bilan-paysage",
    name: "Bilan Paysage",
    title: "Bilan en Format Paysage",
    description: "État de la situation financière en format paysage",
    category: "États",
    component: BilanPaysage,
    icon: <Monitor className="h-6 w-6 text-purple-600" />,
    reportType: "normal",
  },

  // Assurance Reports
  {
    id: "assurance-bilan-actif",
    name: "Bilan Actif - Assurance",
    title: "Bilan Actif Sectoriel",
    description: "État de l'actif pour les entreprises d'assurance",
    category: "Assurance",
    component: BilanActif,
    icon: <Building className="h-6 w-6 text-blue-600" />,
    reportType: "assurance",
  },
  {
    id: "assurance-bilan-passif",
    name: "Bilan Passif - Assurance",
    title: "Bilan Passif Sectoriel",
    description: "État du passif pour les entreprises d'assurance",
    category: "Assurance",
    component: BilanPassif,
    icon: <Building className="h-6 w-6 text-green-600" />,
    reportType: "assurance",
  },
  {
    id: "assurance-charges",
    name: "Charges - Assurance",
    title: "Charges d'Exploitation Assurance",
    description: "Charges d'exploitation spécifiques aux assurances",
    category: "Assurance",
    component: Charges,
    icon: <Calculator className="h-6 w-6 text-red-600" />,
    reportType: "assurance",
  },
  {
    id: "assurance-compte-general",
    name: "Compte Général - Assurance",
    title: "Compte de Résultat Général",
    description: "État des résultats généraux pour assurances",
    category: "Assurance",
    component: CompteGeneralPertesProfits,
    icon: <BarChart className="h-6 w-6 text-purple-600" />,
    reportType: "assurance",
  },
  {
    id: "assurance-etat-c4",
    name: "État C4 - Assurance",
    title: "État C4 Sectoriel",
    description: "État réglementaire C4 pour les assurances",
    category: "Assurance",
    component: EtatC4,
    icon: <FileText className="h-6 w-6 text-indigo-600" />,
    reportType: "assurance",
  },
  {
    id: "assurance-etat-c11",
    name: "État C11 - Assurance",
    title: "État C11 Sectoriel",
    description: "État réglementaire C11 pour les assurances",
    category: "Assurance",
    component: EtatC11,
    icon: <FileText className="h-6 w-6 text-teal-600" />,
    reportType: "assurance",
  },
  {
    id: "assurance-etat-c11-vie",
    name: "État C11 Vie - Assurance",
    title: "État C11 Vie Sectoriel",
    description: "État réglementaire C11 Vie pour les assurances",
    category: "Assurance",
    component: EtatC11Vie,
    icon: <FileText className="h-6 w-6 text-cyan-600" />,
    reportType: "assurance",
  },
  {
    id: "assurance-produits",
    name: "Produits - Assurance",
    title: "Produits d'Exploitation Assurance",
    description: "Produits d'exploitation spécifiques aux assurances",
    category: "Assurance",
    component: Produits,
    icon: <TrendingUp className="h-6 w-6 text-emerald-600" />,
    reportType: "assurance",
  },
  {
    id: "assurance-ass1",
    name: "Assurance 1",
    title: "Rapport Assurance 1",
    description: "Premier rapport spécifique aux assurances",
    category: "Assurance",
    component: Ass1,
    icon: <FileText className="h-6 w-6 text-blue-600" />,
    reportType: "assurance",
  },
  {
    id: "assurance-ass2",
    name: "Assurance 2",
    title: "Rapport Assurance 2",
    description: "Deuxième rapport spécifique aux assurances",
    category: "Assurance",
    component: Ass2,
    icon: <FileText className="h-6 w-6 text-green-600" />,
    reportType: "assurance",
  },
  {
    id: "assurance-ass3",
    name: "Assurance 3",
    title: "Rapport Assurance 3",
    description: "Troisième rapport spécifique aux assurances",
    category: "Assurance",
    component: Ass3,
    icon: <FileText className="h-6 w-6 text-purple-600" />,
    reportType: "assurance",
  },
  {
    id: "assurance-ass4",
    name: "Assurance 4",
    title: "Rapport Assurance 4",
    description: "Quatrième rapport spécifique aux assurances",
    category: "Assurance",
    component: Ass4,
    icon: <FileText className="h-6 w-6 text-red-600" />,
    reportType: "assurance",
  },
  {
    id: "assurance-ass5",
    name: "Assurance 5",
    title: "Rapport Assurance 5",
    description: "Cinquième rapport spécifique aux assurances",
    category: "Assurance",
    component: Ass5,
    icon: <FileText className="h-6 w-6 text-orange-600" />,
    reportType: "assurance",
  },
  {
    id: "assurance-ass6",
    name: "Assurance 6",
    title: "Rapport Assurance 6",
    description: "Sixième rapport spécifique aux assurances",
    category: "Assurance",
    component: Ass6,
    icon: <FileText className="h-6 w-6 text-cyan-600" />,
    reportType: "assurance",
  },
  {
    id: "assurance-ass7",
    name: "Assurance 7",
    title: "Rapport Assurance 7",
    description: "Septième rapport spécifique aux assurances",
    category: "Assurance",
    component: Ass7,
    icon: <FileText className="h-6 w-6 text-emerald-600" />,
    reportType: "assurance",
  },
  {
    id: "assurance-ass8",
    name: "Assurance 8",
    title: "Rapport Assurance 8",
    description: "Huitième rapport spécifique aux assurances",
    category: "Assurance",
    component: Ass8,
    icon: <FileText className="h-6 w-6 text-indigo-600" />,
    reportType: "assurance",
  },
  {
    id: "assurance-ass9",
    name: "Assurance 9",
    title: "Rapport Assurance 9",
    description: "Neuvième rapport spécifique aux assurances",
    category: "Assurance",
    component: Ass9,
    icon: <FileText className="h-6 w-6 text-pink-600" />,
    reportType: "assurance",
  },
  {
    id: "assurance-ass10",
    name: "Assurance 10",
    title: "Rapport Assurance 10",
    description: "Dixième rapport spécifique aux assurances",
    category: "Assurance",
    component: Ass10,
    icon: <FileText className="h-6 w-6 text-teal-600" />,
    reportType: "assurance",
  },
  {
    id: "assurance-ass11",
    name: "Assurance 11",
    title: "Rapport Assurance 11",
    description: "Onzième rapport spécifique aux assurances",
    category: "Assurance",
    component: Ass11,
    icon: <FileText className="h-6 w-6 text-gray-600" />,
    reportType: "assurance",
  },
  {
    id: "assurance-declaration-annuel",
    name: "Déclaration Annuelle",
    title: "Déclaration Annuelle d'Assurance",
    description: "Déclaration annuelle pour les entreprises d'assurance",
    category: "Assurance",
    component: DeclarationAnnuel,
    icon: <FileText className="h-6 w-6 text-blue-600" />,
    reportType: "assurance",
  },
  {
    id: "assurance-sommes-verse",
    name: "Sommes Versées",
    title: "Sommes Versées Assurance",
    description: "État des sommes versées par les assurances",
    category: "Assurance",
    component: SommesVerse,
    icon: <Calculator className="h-6 w-6 text-green-600" />,
    reportType: "assurance",
  },
  {
    id: "assurance-tva",
    name: "TVA Assurance",
    title: "Taxe sur la Valeur Ajoutée Assurance",
    description: "Calcul de la TVA pour les entreprises d'assurance",
    category: "Assurance",
    component: TVA,
    icon: <Calculator className="h-6 w-6 text-purple-600" />,
    reportType: "assurance",
  },
  {
    id: "assurance-versements",
    name: "Versements Assurance",
    title: "Versements d'Assurance",
    description: "État des versements effectués par les assurances",
    category: "Assurance",
    component: Versements,
    icon: <CreditCard className="h-6 w-6 text-red-600" />,
    reportType: "assurance",
  },
  {
    id: "assurance-tableau-30",
    name: "Tableau 30",
    title: "Tableau 30 - Assurance",
    description: "Tableau réglementaire 30 pour assurances",
    category: "Assurance",
    component: Tableau30,
    icon: <Grid3X3 className="h-6 w-6 text-orange-600" />,
    reportType: "assurance",
  },
  {
    id: "assurance-tableau-31",
    name: "Tableau 31",
    title: "Tableau 31 - Assurance",
    description: "Tableau réglementaire 31 pour assurances",
    category: "Assurance",
    component: Tableau31,
    icon: <Grid3X3 className="h-6 w-6 text-cyan-600" />,
    reportType: "assurance",
  },
  {
    id: "assurance-tableau-32",
    name: "Tableau 32",
    title: "Tableau 32 - Assurance",
    description: "Tableau réglementaire 32 pour assurances",
    category: "Assurance",
    component: Tableau32,
    icon: <Grid3X3 className="h-6 w-6 text-emerald-600" />,
    reportType: "assurance",
  },
  {
    id: "assurance-tableau-33",
    name: "Tableau 33",
    title: "Tableau 33 - Assurance",
    description: "Tableau réglementaire 33 pour assurances",
    category: "Assurance",
    component: Tableau33,
    icon: <Grid3X3 className="h-6 w-6 text-indigo-600" />,
    reportType: "assurance",
  },
  {
    id: "assurance-tableau-34",
    name: "Tableau 34",
    title: "Tableau 34 - Assurance",
    description: "Tableau réglementaire 34 pour assurances",
    category: "Assurance",
    component: Tableau34,
    icon: <Grid3X3 className="h-6 w-6 text-pink-600" />,
    reportType: "assurance",
  },
  {
    id: "assurance-tableau-35a",
    name: "Tableau 35A",
    title: "Tableau 35A - Assurance",
    description: "Tableau réglementaire 35A pour assurances",
    category: "Assurance",
    component: Tableau35A,
    icon: <Grid3X3 className="h-6 w-6 text-teal-600" />,
    reportType: "assurance",
  },
  {
    id: "assurance-tableau-35b",
    name: "Tableau 35B",
    title: "Tableau 35B - Assurance",
    description: "Tableau réglementaire 35B pour assurances",
    category: "Assurance",
    component: Tableau35B,
    icon: <Grid3X3 className="h-6 w-6 text-gray-600" />,
    reportType: "assurance",
  },
  {
    id: "assurance-tableau-36",
    name: "Tableau 36",
    title: "Tableau 36 - Assurance",
    description: "Tableau réglementaire 36 pour assurances",
    category: "Assurance",
    component: Tableau36,
    icon: <Grid3X3 className="h-6 w-6 text-blue-600" />,
    reportType: "assurance",
  },
  {
    id: "assurance-tableau-37",
    name: "Tableau 37",
    title: "Tableau 37 - Assurance",
    description: "Tableau réglementaire 37 pour assurances",
    category: "Assurance",
    component: Tableau37,
    icon: <Grid3X3 className="h-6 w-6 text-green-600" />,
    reportType: "assurance",
  },
  {
    id: "assurance-tableau-38",
    name: "Tableau 38",
    title: "Tableau 38 - Assurance",
    description: "Tableau réglementaire 38 pour assurances",
    category: "Assurance",
    component: Tableau38,
    icon: <Grid3X3 className="h-6 w-6 text-purple-600" />,
    reportType: "assurance",
  },
  {
    id: "assurance-tableau-39",
    name: "Tableau 39",
    title: "Tableau 39 - Assurance",
    description: "Tableau réglementaire 39 pour assurances",
    category: "Assurance",
    component: Tableau39,
    icon: <Grid3X3 className="h-6 w-6 text-red-600" />,
    reportType: "assurance",
  },
  {
    id: "assurance-tableau-40",
    name: "Tableau 40",
    title: "Tableau 40 - Assurance",
    description: "Tableau réglementaire 40 pour assurances",
    category: "Assurance",
    component: Tableau40,
    icon: <Grid3X3 className="h-6 w-6 text-orange-600" />,
    reportType: "assurance",
  },
  {
    id: "assurance-tableau-41a",
    name: "Tableau 41A",
    title: "Tableau 41A - Assurance",
    description: "Tableau réglementaire 41A pour assurances",
    category: "Assurance",
    component: Tableau41A,
    icon: <Grid3X3 className="h-6 w-6 text-cyan-600" />,
    reportType: "assurance",
  },
  {
    id: "assurance-tableau-41b",
    name: "Tableau 41B",
    title: "Tableau 41B - Assurance",
    description: "Tableau réglementaire 41B pour assurances",
    category: "Assurance",
    component: Tableau41B,
    icon: <Grid3X3 className="h-6 w-6 text-emerald-600" />,
    reportType: "assurance",
  },
  {
    id: "assurance-tableau-42",
    name: "Tableau 42",
    title: "Tableau 42 - Assurance",
    description: "Tableau réglementaire 42 pour assurances",
    category: "Assurance",
    component: Tableau42,
    icon: <Grid3X3 className="h-6 w-6 text-indigo-600" />,
    reportType: "assurance",
  },
  {
    id: "assurance-tableau-43a",
    name: "Tableau 43A",
    title: "Tableau 43A - Assurance",
    description: "Tableau réglementaire 43A pour assurances",
    category: "Assurance",
    component: Tableau43A,
    icon: <Grid3X3 className="h-6 w-6 text-pink-600" />,
    reportType: "assurance",
  },
  {
    id: "assurance-tableau-43b",
    name: "Tableau 43B",
    title: "Tableau 43B - Assurance",
    description: "Tableau réglementaire 43B pour assurances",
    category: "Assurance",
    component: Tableau43B,
    icon: <Grid3X3 className="h-6 w-6 text-teal-600" />,
    reportType: "assurance",
  },
  {
    id: "assurance-tableau-44a",
    name: "Tableau 44A",
    title: "Tableau 44A - Assurance",
    description: "Tableau réglementaire 44A pour assurances",
    category: "Assurance",
    component: Tableau44A,
    icon: <Grid3X3 className="h-6 w-6 text-gray-600" />,
    reportType: "assurance",
  },
  {
    id: "assurance-annexe-6",
    name: "Annexe 6",
    title: "Annexe 6 - Assurance",
    description: "Annexe 6 pour les entreprises d'assurance",
    category: "Assurance",
    component: Annexe6,
    icon: <FileText className="h-6 w-6 text-blue-600" />,
    reportType: "assurance",
  },

  // SMT Reports
  {
    id: "smt-grille-analyse-notes",
    name: "Grille Analyse Notes SMT",
    title: "Grille d'Analyse des Notes SMT",
    description:
      "Grille d'analyse structurée des notes pour les sociétés de microfinance",
    category: "SMT",
    component: GrilleAnalyseNotesSMT,
    icon: <Grid3X3 className="h-6 w-6 text-indigo-600" />,
    reportType: "smt",
  },
  {
    id: "smt-mod-bilan",
    name: "Modèle Bilan SMT",
    title: "Modèle de Bilan SMT",
    description: "Modèle de bilan pour les sociétés de microfinance",
    category: "SMT",
    component: ModBilan,
    icon: <FileText className="h-6 w-6 text-blue-600" />,
    reportType: "smt",
  },
  {
    id: "smt-note-1",
    name: "Note 1 SMT",
    title: "Sommaire du Matériel SMT",
    description: "Sommaire du matériel, mobilier et cautions pour SMT",
    category: "SMT",
    component: Note1Smt,
    icon: <FileText className="h-6 w-6 text-blue-600" />,
    reportType: "smt",
  },
  {
    id: "smt-note-2",
    name: "Note 2 SMT",
    title: "États des Stocks SMT",
    description: "États des stocks pour les sociétés de microfinance",
    category: "SMT",
    component: Note2Smt,
    icon: <FileSpreadsheet className="h-6 w-6 text-yellow-600" />,
    reportType: "smt",
  },
  {
    id: "smt-note-3",
    name: "Note 3 SMT",
    title: "Créances et Dettes SMT",
    description: "État des créances et dettes non échues pour SMT",
    category: "SMT",
    component: Note3Smt,
    icon: <Users className="h-6 w-6 text-cyan-600" />,
    reportType: "smt",
  },
  {
    id: "smt-note-4",
    name: "Note 4 SMT",
    title: "Journal Trésorerie SMT",
    description: "Journal des trésoreries pour les sociétés de microfinance",
    category: "SMT",
    component: Note4Smt,
    icon: <CreditCard className="h-6 w-6 text-emerald-600" />,
    reportType: "smt",
  },
  {
    id: "smt-note-5",
    name: "Note 5 SMT",
    title: "Créances Impayées SMT",
    description: "Journal des sommes des créances impayées pour SMT",
    category: "SMT",
    component: Note5Smt,
    icon: <Users className="h-6 w-6 text-red-600" />,
    reportType: "smt",
  },
  {
    id: "smt-note-6",
    name: "Note 6 SMT",
    title: "Dettes à Payer SMT",
    description: "Journal des sommes des dettes à payer pour SMT",
    category: "SMT",
    component: Note6Smt,
    icon: <FileText className="h-6 w-6 text-orange-600" />,
    reportType: "smt",
  },
  {
    id: "smt-t1",
    name: "T1 SMT",
    title: "Immobilisations Brutes SMT",
    description: "Tableau des immobilisations brutes pour SMT",
    category: "SMT",
    component: T1,
    icon: <Building className="h-6 w-6 text-purple-600" />,
    reportType: "smt",
  },
  {
    id: "smt-t1-bis",
    name: "T1 Bis SMT",
    title: "Amortissements Différés SMT",
    description: "Immobilisations amortissements déductibles réputés pour SMT",
    category: "SMT",
    component: T1Bis,
    icon: <Calculator className="h-6 w-6 text-red-600" />,
    reportType: "smt",
  },
  {
    id: "smt-t1-ter",
    name: "T1 Ter SMT",
    title: "Somme Amortissements SMT",
    description:
      "Tableau de somme des amortissements déductibles réputés différés",
    category: "SMT",
    component: T1Ter,
    icon: <Calculator className="h-6 w-6 text-teal-600" />,
    reportType: "smt",
  },
  {
    id: "smt-t2",
    name: "T2 SMT",
    title: "Plus/Moins Values SMT",
    description:
      "Immobilisations plus-values et moins-values de cession pour SMT",
    category: "SMT",
    component: T2,
    icon: <TrendingUp className="h-6 w-6 text-green-600" />,
    reportType: "smt",
  },
  {
    id: "smt-t3",
    name: "T3 SMT",
    title: "Immobilisations Financières SMT",
    description:
      "Immobilisations financières pour les sociétés de microfinance",
    category: "SMT",
    component: T3,
    icon: <CreditCard className="h-6 w-6 text-indigo-600" />,
    reportType: "smt",
  },
  {
    id: "smt-t4",
    name: "T4 SMT",
    title: "Balance Fournisseurs SMT",
    description: "Extrait de la balance générale des fournisseurs pour SMT",
    category: "SMT",
    component: T4,
    icon: <Users className="h-6 w-6 text-cyan-600" />,
    reportType: "smt",
  },
  {
    id: "smt-t5",
    name: "T5 SMT",
    title: "Synthèse Impôts SMT",
    description: "Synthèse des impôts et taxes versés pour SMT",
    category: "SMT",
    component: T5,
    icon: <Calculator className="h-6 w-6 text-blue-600" />,
    reportType: "smt",
  },
  {
    id: "smt-t6",
    name: "T6 SMT",
    title: "Passage Résultat Fiscal SMT",
    description:
      "Tableau de passage du résultat comptable au résultat fiscal pour SMT",
    category: "SMT",
    component: T6,
    icon: <Calculator className="h-6 w-6 text-red-600" />,
    reportType: "smt",
  },
  {
    id: "smt-t7",
    name: "T7 SMT",
    title: "Impôt Bénéfice Fiscal SMT",
    description:
      "Tableau de détermination de l'impôt sur le bénéfice fiscal pour SMT",
    category: "SMT",
    component: T7,
    icon: <Calculator className="h-6 w-6 text-orange-600" />,
    reportType: "smt",
  },
  {
    id: "smt-t8",
    name: "T8 SMT",
    title: "Minimum Perception SMT",
    description: "Tableau de détermination du minimum de perception pour SMT",
    category: "SMT",
    component: T8,
    icon: <Calculator className="h-6 w-6 text-cyan-600" />,
    reportType: "smt",
  },
  {
    id: "smt-t9",
    name: "T9 SMT",
    title: "Perception SMT",
    description: "Tableau de détermination de la perception pour SMT",
    category: "SMT",
    component: T9,
    icon: <Calculator className="h-6 w-6 text-emerald-600" />,
    reportType: "smt",
  },
] as const satisfies NoteItem[];

export const NOTES_DATA_MUTABLE: NoteItem[] = NOTES_DATA.map(item => ({ ...item })).sort((a, b) => a.name.localeCompare(b.name));

export const getCategoriesForReportType = (
  reportType: "normal" | "smt" | "assurance" | null
): string[] => {
  const filteredNotes = reportType
    ? NOTES_DATA.filter((note) => note.reportType === reportType)
    : NOTES_DATA;

  const categories = new Set(filteredNotes.map((note) => note.category));
  return Array.from(categories).sort();
};

export const getNotesForCategory = (
  category: string,
  reportType: "normal" | "smt" | "assurance" | null
): NoteItem[] => {
  return NOTES_DATA.filter((note) => {
    const matchesCategory = note.category === category;
    const matchesReportType = reportType
      ? note.reportType === reportType
      : true;
    return matchesCategory && matchesReportType;
  });
};
