import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "./ui/card";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "./ui/tabs";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "./ui/table";
import { Button } from "./ui/button";
import { Badge } from "./ui/badge";
import { Input } from "./ui/input";
import { Label } from "./ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "./ui/select";
import { Progress } from "./ui/progress";
import { Alert, AlertDescription } from "./ui/alert";
import { 
  Upload, 
  Download, 
  FileText, 
  Image, 
  Scan,
  Search,
  Filter,
  FolderOpen,
  Clock,
  Eye,
  Share,
  Lock,
  CheckCircle,
  AlertTriangle,
  Bot,
  Archive
} from 'lucide-react';

const documents = [
  { 
    id: 'DOC-001', 
    name: 'Monthly P&L Statement - January 2024.pdf', 
    type: 'Financial Report', 
    size: '2.4 MB', 
    uploadDate: '2024-01-15', 
    status: 'Processed', 
    autoGenerated: true,
    tags: ['financial', 'monthly', 'p&l'],
    version: '1.2'
  },
  { 
    id: 'DOC-002', 
    name: 'Bank Statement - Chase December.pdf', 
    type: 'Bank Statement', 
    size: '1.8 MB', 
    uploadDate: '2024-01-10', 
    status: 'Processed', 
    autoGenerated: false,
    tags: ['bank', 'statement', 'december'],
    version: '1.0'
  },
  { 
    id: 'DOC-003', 
    name: 'Tax Return Draft - ABC Corp 2023.pdf', 
    type: 'Tax Document', 
    size: '5.2 MB', 
    uploadDate: '2024-01-08', 
    status: 'Under Review', 
    autoGenerated: true,
    tags: ['tax', 'return', '2023'],
    version: '2.1'
  },
  { 
    id: 'DOC-004', 
    name: 'Expense Receipts - Q4 2023.zip', 
    type: 'Receipts', 
    size: '15.7 MB', 
    uploadDate: '2024-01-05', 
    status: 'Processing', 
    autoGenerated: false,
    tags: ['receipts', 'expenses', 'q4'],
    version: '1.0'
  },
  { 
    id: 'DOC-005', 
    name: 'Audit Response Letter - Manufacturing Co.pdf', 
    type: 'Audit Document', 
    size: '890 KB', 
    uploadDate: '2024-01-12', 
    status: 'Approved', 
    autoGenerated: true,
    tags: ['audit', 'response', 'manufacturing'],
    version: '1.0'
  }
];

const documentTemplates = [
  { name: 'Monthly Financial Package', type: 'Report Bundle', files: 8, lastUsed: '2024-01-01' },
  { name: 'Tax Return Preparation Kit', type: 'Tax Bundle', files: 12, lastUsed: '2024-01-08' },
  { name: 'Client Onboarding Documents', type: 'Client Bundle', files: 6, lastUsed: '2024-01-10' },
  { name: 'Audit Response Package', type: 'Audit Bundle', files: 4, lastUsed: '2024-01-12' },
  { name: 'Quarterly Board Reports', type: 'Board Bundle', files: 15, lastUsed: '2023-12-30' },
];

const ocrJobs = [
  { id: 'OCR-001', document: 'Expense Receipt Batch #47', pages: 23, progress: 87, status: 'Processing' },
  { id: 'OCR-002', document: 'Bank Statements Q4', pages: 156, progress: 100, status: 'Completed' },
  { id: 'OCR-003', document: 'Invoice Batch #128', pages: 45, progress: 45, status: 'Processing' },
  { id: 'OCR-004', document: 'Tax Documents 2023', pages: 89, progress: 0, status: 'Queued' },
];

const approvalWorkflows = [
  { id: 'WF-001', document: 'Monthly P&L Statement', assignee: 'Sarah Wilson', status: 'Pending', daysRemaining: 2 },
  { id: 'WF-002', document: 'Tax Return - TechCorp', assignee: 'Mike Johnson', status: 'Under Review', daysRemaining: 5 },
  { id: 'WF-003', document: 'Audit Response Letter', assignee: 'Emily Chen', status: 'Approved', daysRemaining: 0 },
  { id: 'WF-004', document: 'Budget Variance Report', assignee: 'David Rodriguez', status: 'Rejected', daysRemaining: 0 },
];

export function DocumentManagement() {
  return (
    <div className="space-y-6">
      <div className="flex justify-between items-center">
        <div>
          <h2>Document Management</h2>
          <p className="text-muted-foreground">Automated document processing, storage, and workflow management</p>
        </div>
        <div className="flex gap-2">
          <Button>
            <Upload className="h-4 w-4 mr-2" />
            Upload Documents
          </Button>
          <Button variant="outline">
            <Scan className="h-4 w-4 mr-2" />
            Start OCR
          </Button>
        </div>
      </div>

      {/* Document Processing Status */}
      <div className="grid grid-cols-1 md:grid-cols-4 gap-4">
        <Card>
          <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
            <CardTitle>Total Documents</CardTitle>
            <FileText className="h-4 w-4 text-muted-foreground" />
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold">2,847</div>
            <p className="text-xs text-muted-foreground">+127 this month</p>
          </CardContent>
        </Card>
        <Card>
          <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
            <CardTitle>Auto-Generated</CardTitle>
            <Bot className="h-4 w-4 text-muted-foreground" />
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold">1,429</div>
            <p className="text-xs text-muted-foreground">50.2% automated</p>
          </CardContent>
        </Card>
        <Card>
          <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
            <CardTitle>OCR Processed</CardTitle>
            <Scan className="h-4 w-4 text-muted-foreground" />
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold">892</div>
            <p className="text-xs text-muted-foreground">94.2% accuracy</p>
          </CardContent>
        </Card>
        <Card>
          <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
            <CardTitle>Storage Used</CardTitle>
            <Archive className="h-4 w-4 text-muted-foreground" />
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold">47.2 GB</div>
            <p className="text-xs text-muted-foreground">78% of quota</p>
          </CardContent>
        </Card>
      </div>

      <Tabs defaultValue="documents" className="space-y-6">
        <TabsList>
          <TabsTrigger value="documents">Document Library</TabsTrigger>
          <TabsTrigger value="templates">Templates</TabsTrigger>
          <TabsTrigger value="ocr">OCR Processing</TabsTrigger>
          <TabsTrigger value="approval">Approval Workflows</TabsTrigger>
        </TabsList>

        <TabsContent value="documents" className="space-y-4">
          <Card>
            <CardHeader>
              <CardTitle>Document Library</CardTitle>
              <CardDescription>Centralized repository for all financial documents</CardDescription>
            </CardHeader>
            <CardContent>
              <div className="flex justify-between items-center mb-4">
                <div className="flex gap-2">
                  <div className="relative">
                    <Search className="h-4 w-4 absolute left-3 top-1/2 transform -translate-y-1/2 text-muted-foreground" />
                    <Input placeholder="Search documents..." className="pl-9 w-64" />
                  </div>
                  <Select>
                    <SelectTrigger className="w-40">
                      <SelectValue placeholder="Document Type" />
                    </SelectTrigger>
                    <SelectContent>
                      <SelectItem value="all">All Types</SelectItem>
                      <SelectItem value="financial">Financial Reports</SelectItem>
                      <SelectItem value="tax">Tax Documents</SelectItem>
                      <SelectItem value="bank">Bank Statements</SelectItem>
                      <SelectItem value="receipts">Receipts</SelectItem>
                      <SelectItem value="audit">Audit Documents</SelectItem>
                    </SelectContent>
                  </Select>
                  <Button variant="outline">
                    <Filter className="h-4 w-4 mr-2" />
                    Filters
                  </Button>
                </div>
              </div>
              
              <Table>
                <TableHeader>
                  <TableRow>
                    <TableHead>Document Name</TableHead>
                    <TableHead>Type</TableHead>
                    <TableHead>Size</TableHead>
                    <TableHead>Upload Date</TableHead>
                    <TableHead>Status</TableHead>
                    <TableHead>Version</TableHead>
                    <TableHead>Auto-Gen</TableHead>
                    <TableHead className="text-right">Actions</TableHead>
                  </TableRow>
                </TableHeader>
                <TableBody>
                  {documents.map((doc) => (
                    <TableRow key={doc.id}>
                      <TableCell>
                        <div className="flex items-center gap-2">
                          <FileText className="h-4 w-4 text-muted-foreground" />
                          <div>
                            <p className="font-medium">{doc.name}</p>
                            <div className="flex gap-1 mt-1">
                              {doc.tags.map((tag, index) => (
                                <Badge key={index} variant="outline" className="text-xs">
                                  {tag}
                                </Badge>
                              ))}
                            </div>
                          </div>
                        </div>
                      </TableCell>
                      <TableCell>
                        <Badge variant="secondary">{doc.type}</Badge>
                      </TableCell>
                      <TableCell>{doc.size}</TableCell>
                      <TableCell>{doc.uploadDate}</TableCell>
                      <TableCell>
                        <Badge variant={
                          doc.status === 'Processed' ? 'default' :
                          doc.status === 'Approved' ? 'secondary' :
                          doc.status === 'Processing' ? 'outline' : 'destructive'
                        }>
                          {doc.status}
                        </Badge>
                      </TableCell>
                      <TableCell>{doc.version}</TableCell>
                      <TableCell>
                        {doc.autoGenerated ? (
                          <CheckCircle className="h-4 w-4 text-green-500" />
                        ) : (
                          <div className="h-4 w-4" />
                        )}
                      </TableCell>
                      <TableCell className="text-right">
                        <div className="flex justify-end gap-1">
                          <Button variant="outline" size="sm">
                            <Eye className="h-3 w-3" />
                          </Button>
                          <Button variant="outline" size="sm">
                            <Download className="h-3 w-3" />
                          </Button>
                          <Button variant="outline" size="sm">
                            <Share className="h-3 w-3" />
                          </Button>
                        </div>
                      </TableCell>
                    </TableRow>
                  ))}
                </TableBody>
              </Table>
            </CardContent>
          </Card>
        </TabsContent>

        <TabsContent value="templates" className="space-y-4">
          <Card>
            <CardHeader>
              <CardTitle>Document Templates</CardTitle>
              <CardDescription>Pre-configured document packages for common workflows</CardDescription>
            </CardHeader>
            <CardContent>
              <div className="flex justify-between items-center mb-4">
                <Button>
                  <FolderOpen className="h-4 w-4 mr-2" />
                  Create Template
                </Button>
              </div>
              
              <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
                {documentTemplates.map((template, index) => (
                  <Card key={index}>
                    <CardHeader className="pb-3">
                      <CardTitle className="text-base">{template.name}</CardTitle>
                      <CardDescription className="text-sm">{template.type}</CardDescription>
                    </CardHeader>
                    <CardContent>
                      <div className="space-y-3">
                        <div className="flex justify-between text-sm">
                          <span>Files included:</span>
                          <span className="font-medium">{template.files}</span>
                        </div>
                        <div className="flex justify-between text-sm">
                          <span>Last used:</span>
                          <span className="text-muted-foreground">{template.lastUsed}</span>
                        </div>
                        <div className="flex gap-2">
                          <Button size="sm" className="flex-1">Use Template</Button>
                          <Button size="sm" variant="outline">Edit</Button>
                        </div>
                      </div>
                    </CardContent>
                  </Card>
                ))}
              </div>
            </CardContent>
          </Card>

          {/* Auto-Generation Settings */}
          <Card>
            <CardHeader>
              <CardTitle>Automatic Document Generation</CardTitle>
              <CardDescription>Configure which documents should be automatically generated</CardDescription>
            </CardHeader>
            <CardContent>
              <div className="space-y-4">
                <Alert>
                  <CheckCircle className="h-4 w-4" />
                  <AlertDescription>
                    Document automation is saving approximately <strong>15 hours per week</strong> by auto-generating routine reports and forms.
                  </AlertDescription>
                </Alert>
                
                <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                  <div className="space-y-2">
                    <Label>Financial Reports</Label>
                    <div className="space-y-2">
                      <div className="flex items-center justify-between">
                        <span className="text-sm">Monthly P&L Statement</span>
                        <Badge variant="default">Enabled</Badge>
                      </div>
                      <div className="flex items-center justify-between">
                        <span className="text-sm">Cash Flow Report</span>
                        <Badge variant="default">Enabled</Badge>
                      </div>
                      <div className="flex items-center justify-between">
                        <span className="text-sm">Balance Sheet</span>
                        <Badge variant="outline">Disabled</Badge>
                      </div>
                    </div>
                  </div>
                  
                  <div className="space-y-2">
                    <Label>Tax Documents</Label>
                    <div className="space-y-2">
                      <div className="flex items-center justify-between">
                        <span className="text-sm">Quarterly Estimates</span>
                        <Badge variant="default">Enabled</Badge>
                      </div>
                      <div className="flex items-center justify-between">
                        <span className="text-sm">Form 1120 Draft</span>
                        <Badge variant="outline">Disabled</Badge>
                      </div>
                      <div className="flex items-center justify-between">
                        <span className="text-sm">Depreciation Schedule</span>
                        <Badge variant="default">Enabled</Badge>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </CardContent>
          </Card>
        </TabsContent>

        <TabsContent value="ocr" className="space-y-4">
          <Card>
            <CardHeader>
              <CardTitle>OCR Processing Queue</CardTitle>
              <CardDescription>Optical Character Recognition for automated data extraction</CardDescription>
            </CardHeader>
            <CardContent>
              <div className="space-y-4">
                {ocrJobs.map((job) => (
                  <div key={job.id} className="flex items-center justify-between p-4 border rounded-lg">
                    <div className="flex-1">
                      <div className="flex items-center gap-3 mb-2">
                        <Scan className="h-5 w-5 text-muted-foreground" />
                        <div>
                          <p className="font-medium">{job.document}</p>
                          <p className="text-sm text-muted-foreground">{job.pages} pages</p>
                        </div>
                        <Badge variant={
                          job.status === 'Processing' ? 'default' :
                          job.status === 'Completed' ? 'secondary' : 'outline'
                        }>
                          {job.status}
                        </Badge>
                      </div>
                    </div>
                    <div className="flex items-center gap-3">
                      <div className="w-32">
                        <Progress value={job.progress} className="h-2" />
                      </div>
                      <span className="text-sm font-medium w-12">{job.progress}%</span>
                    </div>
                  </div>
                ))}
              </div>
            </CardContent>
          </Card>

          {/* OCR Accuracy and Settings */}
          <Card>
            <CardHeader>
              <CardTitle>OCR Performance & Settings</CardTitle>
              <CardDescription>Monitor accuracy and configure OCR processing options</CardDescription>
            </CardHeader>
            <CardContent>
              <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                <div className="space-y-4">
                  <div>
                    <div className="flex justify-between items-center mb-2">
                      <span>Overall Accuracy</span>
                      <span className="font-bold">94.2%</span>
                    </div>
                    <Progress value={94.2} className="h-2" />
                  </div>
                  
                  <div>
                    <div className="flex justify-between items-center mb-2">
                      <span>Processing Speed</span>
                      <span className="font-bold">2.3 pages/min</span>
                    </div>
                    <Progress value={85} className="h-2" />
                  </div>
                  
                  <div>
                    <div className="flex justify-between items-center mb-2">
                      <span>Auto-validation Rate</span>
                      <span className="font-bold">87.5%</span>
                    </div>
                    <Progress value={87.5} className="h-2" />
                  </div>
                </div>
                
                <div className="space-y-4">
                  <div>
                    <Label>OCR Engine</Label>
                    <Select>
                      <SelectTrigger>
                        <SelectValue placeholder="Select OCR engine" />
                      </SelectTrigger>
                      <SelectContent>
                        <SelectItem value="advanced">Advanced AI OCR</SelectItem>
                        <SelectItem value="standard">Standard OCR</SelectItem>
                        <SelectItem value="handwriting">Handwriting Recognition</SelectItem>
                      </SelectContent>
                    </Select>
                  </div>
                  
                  <div>
                    <Label>Quality Threshold</Label>
                    <Select>
                      <SelectTrigger>
                        <SelectValue placeholder="Select quality level" />
                      </SelectTrigger>
                      <SelectContent>
                        <SelectItem value="high">High (95%+)</SelectItem>
                        <SelectItem value="medium">Medium (85%+)</SelectItem>
                        <SelectItem value="low">Low (75%+)</SelectItem>
                      </SelectContent>
                    </Select>
                  </div>
                  
                  <Button className="w-full">
                    Save OCR Settings
                  </Button>
                </div>
              </div>
            </CardContent>
          </Card>
        </TabsContent>

        <TabsContent value="approval" className="space-y-4">
          <Card>
            <CardHeader>
              <CardTitle>Document Approval Workflows</CardTitle>
              <CardDescription>Manage document review and approval processes</CardDescription>
            </CardHeader>
            <CardContent>
              <Table>
                <TableHeader>
                  <TableRow>
                    <TableHead>Workflow ID</TableHead>
                    <TableHead>Document</TableHead>
                    <TableHead>Assigned To</TableHead>
                    <TableHead>Status</TableHead>
                    <TableHead>Days Remaining</TableHead>
                    <TableHead className="text-right">Actions</TableHead>
                  </TableRow>
                </TableHeader>
                <TableBody>
                  {approvalWorkflows.map((workflow) => (
                    <TableRow key={workflow.id}>
                      <TableCell>{workflow.id}</TableCell>
                      <TableCell>{workflow.document}</TableCell>
                      <TableCell>{workflow.assignee}</TableCell>
                      <TableCell>
                        <Badge variant={
                          workflow.status === 'Approved' ? 'secondary' :
                          workflow.status === 'Pending' ? 'destructive' :
                          workflow.status === 'Under Review' ? 'default' : 'outline'
                        }>
                          {workflow.status}
                        </Badge>
                      </TableCell>
                      <TableCell>
                        {workflow.daysRemaining > 0 ? (
                          <div className="flex items-center gap-1">
                            <Clock className="h-3 w-3" />
                            {workflow.daysRemaining} days
                          </div>
                        ) : (
                          workflow.status === 'Approved' ? 'Complete' : 'Overdue'
                        )}
                      </TableCell>
                      <TableCell className="text-right">
                        <div className="flex justify-end gap-1">
                          <Button variant="outline" size="sm">
                            <Eye className="h-3 w-3" />
                          </Button>
                          <Button variant="outline" size="sm">
                            <Share className="h-3 w-3" />
                          </Button>
                        </div>
                      </TableCell>
                    </TableRow>
                  ))}
                </TableBody>
              </Table>
            </CardContent>
          </Card>

          {/* Approval Analytics */}
          <Card>
            <CardHeader>
              <CardTitle>Approval Analytics</CardTitle>
              <CardDescription>Track approval workflow performance and bottlenecks</CardDescription>
            </CardHeader>
            <CardContent>
              <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
                <div className="text-center">
                  <div className="text-2xl font-bold">4.2 days</div>
                  <p className="text-sm text-muted-foreground">Average approval time</p>
                </div>
                <div className="text-center">
                  <div className="text-2xl font-bold">92%</div>
                  <p className="text-sm text-muted-foreground">On-time approval rate</p>
                </div>
                <div className="text-center">
                  <div className="text-2xl font-bold">3</div>
                  <p className="text-sm text-muted-foreground">Pending approvals</p>
                </div>
              </div>
            </CardContent>
          </Card>
        </TabsContent>
      </Tabs>
    </div>
  );
}