// AUTO-EXTRACTED from "BASE NOTE HEVEREST 1.xlsx" (feuille "Base à renseigner").
// Chaque entrée correspond à une ligne "feuille" de la table de correspondance:
// le libellé OHADA, les comptes du plan comptable à additionner, et le sens du
// solde à prendre (SD = solde débiteur, SC = solde créditeur).
// Ne pas éditer à la main sans re-générer depuis la source si le fichier Excel change.

export type BalanceSide = 'SD' | 'SC';

export interface MappingLine {
  label: string;
  accounts: string[];
  excludedAccounts?: string[];
  side: BalanceSide;
}

export const ACCOUNT_MAPPING: Record<string, MappingLine[]> = {
  '1': [
    { label: 'Emprunts obligataires convertibles', accounts: ['1612'], side: 'SC' },
    { label: 'Autres emprunts obligataires', accounts: ['1611', '1661', '1613', '1618'], side: 'SC' },
    { label: 'établissements de crédit', accounts: ['162', '1662'], side: 'SC' },
    { label: 'Autres dettes financières', accounts: ['163', '165', '1663', '1664', '1665', '1667', '1668', '167', '168'], side: 'SC' },
    { label: 'Dettes de crédit bail immobilier', accounts: ['172', '1762'], side: 'SC' },
    { label: 'Dettes de crédit bail mobilier', accounts: ['173', '1763'], side: 'SC' },
    { label: 'Dettes sur contrats de location-vente', accounts: ['174', '1764'], side: 'SC' },
    { label: 'Dettes sur contrats de location-acquisition', accounts: ['178', '1768'], side: 'SC' },
    { label: 'Fournisseurs et comptes rattachés', accounts: ['401', '402', '404', '408'], side: 'SC' },
    { label: 'Clients', accounts: ['419'], side: 'SC' },
    { label: 'Personnel', accounts: ['422', '423', '424', '425', '426', '427', '4281', '4286'], side: 'SC' },
    { label: 'Sécurité sociale et organismes sociaux', accounts: ['431', '432', '433', '481', '4382', '4386'], side: 'SC' },
    { label: 'Etat', accounts: ['441', '442', '443', '444', '445', '446', '447', '4486', '4491', '4499'], side: 'SC' },
    { label: 'Organismes internationaux', accounts: ['451', '452'], side: 'SC' },
    { label: 'Associés et groupe', accounts: ['46', '18'], side: 'SC' },
    { label: 'Créditeurs divers', accounts: ['4712'], side: 'SC' },
  ],
  '3A': [
    { label: 'Frais de développement et de prospection', accounts: ['211', '2191'], side: 'SD' },
    { label: 'Brevets, licences, logiciels et droits similaires', accounts: ['212', '213', '214', '2193'], side: 'SD' },
    { label: 'Fonds commercial et droit au bail', accounts: ['215', '216'], side: 'SD' },
    { label: 'Autres immobilisations incorporelles', accounts: ['217', '218', '2198'], side: 'SD' },
    { label: 'Terrains hors immeuble de placement', accounts: ['221', '222', '223', '224', '225', '226', '227', '2285', '2286', '2288', '229'], side: 'SD' },
    { label: 'Terrains - immeuble de placement', accounts: ['2281'], side: 'SD' },
    { label: 'Bâtiments hors immeuble de placement', accounts: ['2311', '2312', '2313', '2314', '2316', '2321', '2322', '2323', '2324', '2326', '233', '237', '2391', '2393'], side: 'SD' },
    { label: 'Bâtiments - immeuble de placement', accounts: ['2315', '2325'], side: 'SD' },
    { label: 'Aménagements, agencements et installations', accounts: ['233', '234', '235', '238', '2392', '2394', '2395', '2398'], side: 'SD' },
    { label: 'Matériel, mobilier et actifs biologiques', accounts: ['241', '242', '243', '244', '246', '247', '248', '2491', '2492', '2493', '2494', '2496', '2497', '2498'], side: 'SD' },
    { label: 'Matériel de transport', accounts: ['245', '2495'], side: 'SD' },
    { label: 'IMMOBILISATIONS INCORPORELLES', accounts: ['251'], side: 'SD' },
    { label: 'IMMOBILISATIONS CORPORELLES', accounts: ['252'], side: 'SD' },
    { label: 'Titres de participation', accounts: ['26'], side: 'SD' },
    { label: 'Autres immobilisations financières', accounts: ['27'], side: 'SD' },
  ],
  '3B': [
    { label: 'S/TOTAL IMMOBILISATIONS INCORPORELLES', accounts: ['121'], side: 'SD' },
    { label: 'S/TOTAL IMMOBILISATIONS CORPORELLES', accounts: ['173'], side: 'SD' },
  ],
  '3C': [
    { label: 'Frais de développement et de prospection', accounts: ['2811'], side: 'SC' },
    { label: 'Brevets, licences, logiciels et droits similaires', accounts: ['2812', '2813', '2814'], side: 'SC' },
    { label: 'Fonds commercial et droit au bail', accounts: ['2815', '2816'], side: 'SC' },
    { label: 'Autres immobilisations incorporelles', accounts: ['2817', '2818'], side: 'SD' },
    { label: 'Terrains hors immeuble de placement', accounts: ['282'], side: 'SC' },
    { label: 'Bâtiments hors immeuble de placement', accounts: ['2831', '2832', '2837'], side: 'SC' },
    { label: 'Aménagements, agencements et installations', accounts: ['2833', '2834', '2835', '2838'], side: 'SC' },
    { label: 'Matériel, mobilier et actifs biologiques', accounts: ['2841', '2842', '2843', '2844', '2847', '2848'], side: 'SC' },
    { label: 'Matériel de transport', accounts: ['2845'], side: 'SD' },
  ],
  '3D': [
    { label: 'S/T IMMOBILISATIONS INCORPORELLES', accounts: ['821'], side: 'SD' },
    { label: 'S/T IMMOBILISATIONS CORPORELLES', accounts: ['822'], side: 'SD' },
    { label: 'S/T IMMOBILISATIONS FINANCIERES', accounts: ['823'], side: 'SD' },
  ],
  '4': [
    { label: 'Titres de participation', accounts: ['26'], side: 'SD' },
    { label: 'Prêts et créances', accounts: ['271'], side: 'SD' },
    { label: 'Prêts au personnel', accounts: ['272'], side: 'SD' },
    { label: 'Créances sur l\'Etat', accounts: ['273'], side: 'SD' },
    { label: 'Titres immobilisés', accounts: ['274'], excludedAccounts: ['2742'], side: 'SD' },
    { label: 'Dépôts et cautionnements', accounts: ['275'], side: 'SD' },
    { label: 'Intérêts couruss', accounts: ['276'], side: 'SD' },
    { label: 'Immobilisations financières diverses', accounts: ['277', '278'], side: 'SD' },
    { label: 'Dépréciations titres de participation', accounts: ['296'], side: 'SC' },
    { label: 'Dépréciations autres immobilisations', accounts: ['297'], side: 'SC' },
  ],
  '5': [
    { label: 'Créances sur cessions d\'immobilisations', accounts: ['485'], side: 'SD' },
    { label: 'Autres créances hors activités ordinaires', accounts: ['488'], side: 'SD' },
    { label: 'Dépréciations des créances H.A.O.', accounts: ['498'], side: 'SC' },
    { label: 'Fournisseurs d\'investissements', accounts: ['4811', '4816', '4817', '4818'], side: 'SC' },
    { label: 'Fournisseurs d\'investissements effets à payer', accounts: ['482'], side: 'SC' },
    { label: 'Versements restant à effectuer sur titres de participation et titres immobilisés non libérés', accounts: ['4813'], side: 'SC' },
    { label: 'Autres dettes hors activités ordinaires', accounts: ['484'], side: 'SC' },
  ],
  '6': [
    { label: 'Marchandises', accounts: ['31'], side: 'SD' },
    { label: 'Matières premières et fournitures liées', accounts: ['32'], side: 'SD' },
    { label: 'Autres approvisionnements', accounts: ['33'], side: 'SD' },
    { label: 'Produits en cours', accounts: ['34'], side: 'SD' },
    { label: 'Services en cours', accounts: ['35'], side: 'SD' },
    { label: 'Produits finis', accounts: ['36'], side: 'SD' },
    { label: 'Produits intermédiaires', accounts: ['37'], side: 'SD' },
    { label: 'Stocks en cours de route, en consignation ou en dépôt', accounts: ['38'], side: 'SD' },
    { label: 'Dépréciations des stocks', accounts: ['39'], side: 'SC' },
  ],
  '7': [
    { label: 'Clients (hors réserve de propriété et Groupe)', accounts: ['4111', '4114', '4115', '4117', '4118'], side: 'SD' },
    { label: 'Clients effets à recevoir (hors réserve de propriété et groupe)', accounts: ['4121', '42124', '4125'], side: 'SD' },
    { label: 'Clients et effets à recevoir avec réserve de propriété', accounts: ['4116'], side: 'SD' },
    { label: 'Clients et effets à recevoir Groupe', accounts: ['4112', '4122'], side: 'SD' },
    { label: 'Clients, chèques, effets et autres valeurs impayés', accounts: ['413'], side: 'SD' },
    { label: 'Créances sur cessions courantes d\'immobilisations', accounts: ['414'], side: 'SD' },
    { label: 'Clients effets eomptés et non échus', accounts: ['415'], side: 'SD' },
    { label: 'Créances litigeuses ou douteuses', accounts: ['416'], side: 'SD' },
    { label: 'Clients produits à recevoir', accounts: ['418'], side: 'SD' },
    { label: 'Dépréciations des comptes clients', accounts: ['491'], side: 'SC' },
    { label: 'Clients, avances reçues hors groupe', accounts: ['4191'], side: 'SC' },
    { label: 'Clients, avances reçues groupe', accounts: ['4192'], side: 'SC' },
    { label: 'Autres clients créditeurs', accounts: ['4194', '4198'], side: 'SC' },
  ],
  '8A': [
    { label: 'FRAIS D\'ETABLISSEMENT', accounts: ['475'], side: 'SD' },
    { label: 'CHARGES A REPARTIR SUR PLUSIEURS EXERCICES', accounts: ['475'], side: 'SD' },
  ],
  '8': [
    { label: 'Personnel', accounts: ['421', '423'], side: 'SD' },
    { label: 'Organismes sociaux', accounts: ['43'], side: 'SD' },
    { label: 'Etat et Collectivités publiques', accounts: ['44'], side: 'SD' },
    { label: 'Organismes internationaux', accounts: ['45'], side: 'SD' },
    { label: 'Apporteurs, associés et groupe', accounts: ['46'], side: 'SD' },
    { label: 'Compte transitoire ajustement spécial lié à la révision du SYSCOHADA', accounts: ['475'], side: 'SD' },
    { label: 'Autres débiteurs divers', accounts: ['471', '472', '473', '474', '476', '477', '478', '479'], side: 'SD' },
    { label: 'Comptes permanents non bloqués des établissements et succursales', accounts: ['185'], side: 'SD' },
    { label: 'Comptes de liaison charges et produits', accounts: ['186', '187'], side: 'SD' },
    { label: 'Comptes de liaison des sociétés en participation', accounts: ['188'], side: 'SD' },
    { label: 'Dépréciations des autres créances', accounts: ['492', '493', '494', '495', '496', '497'], side: 'SC' },
  ],
  '9': [
    { label: 'Titres de trésor et bons de caisse à court terme', accounts: ['501'], side: 'SD' },
    { label: 'Actions', accounts: ['502'], side: 'SD' },
    { label: 'Obligations', accounts: ['503'], side: 'SD' },
    { label: 'Bons de souription', accounts: ['504'], side: 'SD' },
    { label: 'Titres négociables hors régions', accounts: ['505'], side: 'SD' },
    { label: 'Intérêts courus', accounts: ['506'], side: 'SD' },
    { label: 'Autres valeurs assimilées', accounts: ['508'], side: 'SD' },
    { label: 'Dépréciations des titres', accounts: ['590'], side: 'SC' },
  ],
  '10': [
    { label: 'Effets à encaisser', accounts: ['511'], side: 'SD' },
    { label: 'Effets à l\'encaissement', accounts: ['512'], side: 'SD' },
    { label: 'Chèques à encaisser', accounts: ['513'], side: 'SD' },
    { label: 'Chèques à l\'encaissement', accounts: ['514'], side: 'SD' },
    { label: 'Cartes de crédit à encaisser', accounts: ['515'], side: 'SD' },
    { label: 'Autres valeurs à encaisser', accounts: ['518'], side: 'SD' },
    { label: 'Dépréciations des valeurs à encaisser', accounts: ['591'], side: 'SC' },
  ],
  '11': [
    { label: 'Autres établissements financiers', accounts: ['538', '533', '532'], side: 'SD' },
    { label: 'Etablissements financiers intérêts courus', accounts: ['536'], side: 'SD' },
    { label: 'Instruments de trésorerie', accounts: ['54'], side: 'SD' },
    { label: 'Caisse', accounts: ['57'], side: 'SD' },
    { label: 'Caisse électronique mobile', accounts: ['55'], side: 'SD' },
    { label: 'Régies d\'avances et virements accréditifs', accounts: ['58'], side: 'SD' },
    { label: 'Dépréciations', accounts: ['592', '593', '594', '599'], side: 'SC' },
    { label: 'Banques locales', accounts: ['521'], side: 'SD' },
    { label: 'Banques autres états région', accounts: ['522', '523'], side: 'SD' },
    { label: 'Banques, dépôt à terme', accounts: ['525'], side: 'SD' },
    { label: 'Autres banques', accounts: ['524'], side: 'SD' },
    { label: 'Banques intérêts courus', accounts: ['526'], side: 'SD' },
    { label: 'Chèques postaux', accounts: ['531'], side: 'SD' },
  ],
  '12': [
    { label: 'Ecart de conversion - Actifs', accounts: ['478'], side: 'SD' },
    { label: 'Ecart de conversion - Passifs', accounts: ['479'], side: 'SC' },
  ],
  '14': [
    { label: 'Prime d\'émission', accounts: ['1051'], side: 'SC' },
    { label: 'Primes d\'apport', accounts: ['1052'], side: 'SC' },
    { label: 'Prime de fusion', accounts: ['1053'], side: 'SC' },
    { label: 'Prime de conversion', accounts: ['1054'], side: 'SC' },
    { label: 'Autres primes', accounts: ['1058'], side: 'SC' },
    { label: 'Réserves légales', accounts: ['111'], side: 'SC' },
    { label: 'Réserves statutaires', accounts: ['112'], side: 'SC' },
    { label: 'Réserves de plus-values nettes à long terme', accounts: ['1131'], side: 'SC' },
    { label: 'Réserves d\'attribution gratuite d\'actions au pesonnel salarié et aux dirigeants', accounts: ['1132'], side: 'SC' },
    { label: 'Autres réserves réglementées', accounts: ['1133', '1134', '1138'], side: 'SC' },
    { label: 'Réserves libres', accounts: ['118'], side: 'SC' },
    { label: 'Report à nouveau', accounts: ['12'], side: 'SC' },
  ],
  '15A': [
    { label: 'Etat', accounts: ['1411'], side: 'SC' },
    { label: 'Régions', accounts: ['1412'], side: 'SC' },
    { label: 'Départements', accounts: ['1413'], side: 'SC' },
    { label: 'Communes et collectivités publiques décentralisées', accounts: ['1414'], side: 'SC' },
    { label: 'Entités publiques ou mixtes', accounts: ['1415'], side: 'SC' },
    { label: 'Entités et organismes privés', accounts: ['1416'], side: 'SC' },
    { label: 'Organismes internationaux', accounts: ['1417'], side: 'SC' },
    { label: 'Autres', accounts: ['1418', '148'], side: 'SC' },
    { label: 'Amortissements dérogatoires', accounts: ['151'], side: 'SC' },
    { label: 'Plue-value de cession à réinvestir', accounts: ['152'], side: 'SC' },
    { label: 'Provision spéciale de réévaluation', accounts: ['154'], side: 'SC' },
    { label: 'Provisions réglementées relatives aux immobilisations', accounts: ['155'], side: 'SC' },
    { label: 'Provisions réglementées relatives aux stocks', accounts: ['156'], side: 'SC' },
    { label: 'Provisions pour investissement', accounts: ['157'], side: 'SC' },
    { label: 'Autres provisions et fonds réglementés', accounts: ['158', '153'], side: 'SC' },
  ],
  '16A': [
    { label: 'Emprunts obligataires', accounts: ['161'], side: 'SC' },
    { label: 'Emprunts et dettes auprès des établissements crédits', accounts: ['162'], side: 'SC' },
    { label: 'Avances reçues de l\'Etat', accounts: ['163'], side: 'SC' },
    { label: 'Avances reçues et comptes courants bloqués', accounts: ['164'], side: 'SC' },
    { label: 'Dépôts et cautionnements reçus', accounts: ['165'], side: 'SC' },
    { label: 'Intérêts courus1', accounts: ['166'], side: 'SC' },
    { label: 'Avances assorties de conditions particulières', accounts: ['167'], side: 'SC' },
    { label: 'Autres emprunts et dettes', accounts: ['168'], side: 'SC' },
    { label: 'Dettes liées à des participations', accounts: ['181', '182', '183'], side: 'SC' },
    { label: 'Comptes permanents bloqués des établissements et s.', accounts: ['184'], side: 'SC' },
    { label: 'Crédit bail immobilier', accounts: ['172'], side: 'SC' },
    { label: 'Crédit bail mobilier', accounts: ['173'], side: 'SC' },
    { label: 'Location vente', accounts: ['174'], side: 'SC' },
    { label: 'Intérêts courus', accounts: ['176'], side: 'SC' },
    { label: 'Autres dettes de location acquisition', accounts: ['178'], side: 'SC' },
    { label: 'Provisions pour litiges', accounts: ['191'], side: 'SC' },
    { label: 'Provisions pour garantie donnée aux clients', accounts: ['192'], side: 'SC' },
    { label: 'Provisions pour pertes sur marchés à achèvement futur', accounts: ['193'], side: 'SC' },
    { label: 'Provisions pour pertes de change', accounts: ['194'], side: 'SC' },
    { label: 'Provisions pour impôts', accounts: ['195'], side: 'SC' },
    { label: 'Provisions pour pensions et obligations assimilées', accounts: ['1961'], side: 'SC' },
    { label: 'Actif du régime de retraite', accounts: ['1962'], side: 'SC' },
    { label: 'Provisions pour restructuration', accounts: ['197'], side: 'SC' },
    { label: 'Provisions pour amendes et pénalités', accounts: ['1981'], side: 'SC' },
    { label: 'Provisions de propre assureur', accounts: ['1983'], side: 'SC' },
    { label: 'Provisions pour démantèlement et remise en état', accounts: ['1984'], side: 'SC' },
    { label: 'Provisions de droits à déduction', accounts: ['1985'], side: 'SC' },
    { label: 'Autres provisions', accounts: ['1988'], side: 'SC' },
  ],
  '17': [
    { label: 'Fournisseurs dettes en compte (hors groupe)', accounts: ['4011', '4013', '4016', '4017', '4041', '4042'], side: 'SC' },
    { label: 'Fournisseurs effets à payer (hors groupe)', accounts: ['4021', '4023', '4046', '4047'], side: 'SC' },
    { label: 'Fournisseurs dettes et effets à payer groupe', accounts: ['4012', '4022'], side: 'SC' },
    { label: 'Fournisseurs factures non parvenues (hors groupe)', accounts: ['4081', '4083', '4086'], side: 'SC' },
    { label: 'Fournisseurs factures non parvenues groupe', accounts: ['4082'], side: 'SC' },
    { label: 'Fournisseurs, avances et acomptes (hors groupe)', accounts: ['4091'], side: 'SD' },
    { label: 'Fournisseurs, avances et acomptes groupe', accounts: ['4092'], side: 'SD' },
    { label: 'Autres fournisseurs débiteurs', accounts: ['4093', '4094', '4098'], side: 'SD' },
  ],
  '18': [
    { label: 'Personnel avances et acomptes', accounts: ['421'], side: 'SC' },
    { label: 'Personnel rémunérations dues', accounts: ['422'], side: 'SC' },
    { label: 'Autres personnel', accounts: ['423', '424', '425', '426', '427', '428'], side: 'SC' },
    { label: 'Caisse de sécurité sociale', accounts: ['431'], side: 'SC' },
    { label: 'Caisse de retraite', accounts: ['432'], side: 'SC' },
    { label: 'Autres organismes sociaux', accounts: ['433', '438'], side: 'SC' },
    { label: 'Etat, impôts sur les bénéfices', accounts: ['441'], side: 'SC' },
    { label: 'Etat, impôts et taxes', accounts: ['442', '446'], side: 'SC' },
    { label: 'Etat, TVA', accounts: ['443', '444', '445'], side: 'SC' },
    { label: 'Etat, impôts retenus à la source', accounts: ['447'], side: 'SC' },
    { label: 'Autres dettes Etat', accounts: ['448', '449'], side: 'SC' },
  ],
  '19': [
    { label: 'Organismes internationaux', accounts: ['45'], side: 'SC' },
    { label: 'Apporteurs, opérations sur le capital', accounts: ['461'], side: 'SC' },
    { label: 'Associés, compte courant', accounts: ['462'], side: 'SC' },
    { label: 'Associés, dividendes à payer', accounts: ['465'], side: 'SC' },
    { label: 'Groupe, comptes courants', accounts: ['466'], side: 'SC' },
    { label: 'Autres dettes associés', accounts: ['467', '463'], side: 'SC' },
    { label: 'Créditeurs divers', accounts: ['4712'], side: 'SC' },
    { label: 'Obligataires', accounts: ['4713'], side: 'SC' },
    { label: 'Rémunérations d\'administrateurs', accounts: ['4715'], side: 'SC' },
    { label: 'Compte du factor', accounts: ['4716'], side: 'SC' },
    { label: 'Versements restant à effectuer sur titres de placement non libérés', accounts: ['4726'], side: 'SC' },
    { label: 'Compte transitoire ajustement spécial lié à la révision du SYSCOHADA', accounts: ['4752'], side: 'SC' },
    { label: 'Autres créditeurs divers', accounts: ['4711', '4717', '4718', '4719'], side: 'SC' },
    { label: 'Comptes permanents non bloqués des établissements et succursales', accounts: ['185'], side: 'SC' },
    { label: 'Comptes de liaison charges et produits', accounts: ['186'], side: 'SC' },
    { label: 'Comptes de liaison des sociétés en participation', accounts: ['188'], side: 'SC' },
  ],
  '20': [
    { label: 'Escomptes de crédit de campagne', accounts: ['564'], side: 'SC' },
    { label: 'Escomptes de crédit ordinaires', accounts: ['565'], side: 'SC' },
    { label: 'Banques locales', accounts: ['521'], side: 'SC' },
    { label: 'Banques autres états région', accounts: ['522'], side: 'SC' },
    { label: 'Autres banques', accounts: ['523', '524', '525'], side: 'SC' },
    { label: 'Banques intérêts courus', accounts: ['526'], side: 'SC' },
    { label: 'Crédit de trésorerie', accounts: ['561', '566'], side: 'SC' },
  ],
  '21': [
    { label: 'Ventes dans la région', accounts: ['7011'], side: 'SC' },
    { label: 'Ventes hors région', accounts: ['7012'], side: 'SC' },
    { label: 'Ventes groupe', accounts: ['7013', '7014'], side: 'SC' },
    { label: 'Ventes sur internet', accounts: ['7015'], side: 'SC' },
    { label: 'Ventes dans la région1', accounts: ['7021', '7031', '7041'], side: 'SC' },
    { label: 'Ventes hors région1', accounts: ['7022', '7032', '7042'], side: 'SC' },
    { label: 'Ventes groupe1', accounts: ['7023', '7024', '7033', '7034', '7043', '7044'], side: 'SC' },
    { label: 'Ventes sur internet1', accounts: ['7025', '7035', '7045'], side: 'SC' },
    { label: 'Ventes dans la région2', accounts: ['7031', '7061'], side: 'SC' },
    { label: 'Ventes hors région2', accounts: ['7032', '7062'], side: 'SC' },
    { label: 'Ventes groupe2', accounts: ['7033', '7034', '7063', '7064'], side: 'SC' },
    { label: 'Ventes sur internet2', accounts: ['7035', '7065'], side: 'SC' },
    { label: 'Produits accessoires', accounts: ['707'], side: 'SC' },
    { label: 'Production immobilisée', accounts: ['72'], side: 'SC' },
    { label: 'Subventions d\'exploitation', accounts: ['71'], side: 'SC' },
    { label: 'Autres produits', accounts: ['75'], side: 'SC' },
  ],
  '22': [
    { label: 'Achats dans la région', accounts: ['6011'], side: 'SD' },
    { label: 'Achats hors région', accounts: ['6012'], side: 'SD' },
    { label: 'Achats groupe', accounts: ['6013', '6014'], side: 'SD' },
    { label: 'Achats dans la région1', accounts: ['6021'], side: 'SD' },
    { label: 'Achats hors région1', accounts: ['6022'], side: 'SD' },
    { label: 'Achats groupe1', accounts: ['6023', '6024'], side: 'SD' },
    { label: 'Matières consommables', accounts: ['6041'], side: 'SD' },
    { label: 'Matières combustibles', accounts: ['6042'], side: 'SD' },
    { label: 'Produits d\'entretien', accounts: ['6043'], side: 'SD' },
    { label: 'Fournitures d\'atelier, d\'usine et de magasin', accounts: ['6044', '6046', '6047'], side: 'SD' },
    { label: 'Eau', accounts: ['6051'], side: 'SD' },
    { label: 'Electricité', accounts: ['6052'], side: 'SD' },
    { label: 'Autres énergies', accounts: ['6053'], side: 'SD' },
    { label: 'Fourniture d\'entretien', accounts: ['6054'], side: 'SD' },
    { label: 'Fourniture de bureau', accounts: ['6055'], side: 'SD' },
    { label: 'Petit matériel et outillage', accounts: ['6056'], side: 'SD' },
    { label: 'Achats études, prestations de services, de travaux matériels et équipements', accounts: ['6057', '6058'], side: 'SD' },
    { label: 'Achats d\'emballages', accounts: ['6081', '6082', '6083'], side: 'SD' },
    { label: 'Frais sur achats', accounts: ['6015', '6025', '6045', '6085'], side: 'SD' },
    { label: 'Remises rabais, remises et ristournes', accounts: ['6019', '6029', '6049', '6059', '6089'], side: 'SC' },
  ],
  '23': [
    { label: 'Transports sur ventes', accounts: ['612'], side: 'SD' },
    { label: 'Transports pour le compte de tiers', accounts: ['613'], side: 'SD' },
    { label: 'Transport du personnel', accounts: ['614'], side: 'SD' },
    { label: 'Transports de plis', accounts: ['616'], side: 'SD' },
    { label: 'Autres transports', accounts: ['618'], side: 'SD' },
  ],
  '24': [
    { label: 'Sous-traitance générale', accounts: ['621'], side: 'SD' },
    { label: 'Locations et charges locatives', accounts: ['622'], side: 'SD' },
    { label: 'Redevances de location acquisition', accounts: ['623'], side: 'SD' },
    { label: 'Entretien, réparations et maintenance', accounts: ['624'], side: 'SD' },
    { label: 'Primes d\'assurance', accounts: ['625'], side: 'SD' },
    { label: 'Etudes, recherches et documentation', accounts: ['626'], side: 'SD' },
    { label: 'Publicité, publications, relations publiques', accounts: ['627'], side: 'SD' },
    { label: 'Frais de télécommunications', accounts: ['628'], side: 'SD' },
    { label: 'Frais bancaires', accounts: ['631'], side: 'SD' },
    { label: 'Rémunérations d\'intermédiaires et de conseils', accounts: ['632'], side: 'SD' },
    { label: 'Frais de formation du personnel', accounts: ['633'], side: 'SD' },
    { label: 'Redevances pour brevets, licences, logiciels, concession et droits similaires', accounts: ['634'], side: 'SD' },
    { label: 'Cotisations', accounts: ['635'], side: 'SD' },
    { label: 'Autres charges externes', accounts: ['637', '638'], side: 'SD' },
  ],
  '25': [
    { label: 'Impôts et taxes directs', accounts: ['641'], side: 'SD' },
    { label: 'Impôts et taxes indirects', accounts: ['645'], side: 'SD' },
    { label: 'Droits d\'enregistrement', accounts: ['646'], side: 'SD' },
    { label: 'Pénalités et amendes fiscales', accounts: ['647'], side: 'SD' },
    { label: 'Autres impôts et taxes', accounts: ['648'], side: 'SD' },
  ],
  '26': [
    { label: 'Pertes sur créances clients', accounts: ['6511'], side: 'SD' },
    { label: 'Pertes sur autres débiteurs', accounts: ['6515'], side: 'SD' },
    { label: 'Quote-part de résultat sur opérations faites en commun', accounts: ['652'], side: 'SD' },
    { label: 'Valeur comptable des cessions courantes d\'immobilisations', accounts: ['654'], side: 'SD' },
    { label: 'Indemnités de fonction et autres rémunérations d\'administrateurs', accounts: ['6581'], side: 'SD' },
    { label: 'Dons et mécénat', accounts: ['6582', '6583'], side: 'SD' },
    { label: 'Autres charges diverses', accounts: ['6588', '656', '657'], side: 'SD' },
    { label: 'Charges pour dépréciations et provisions pour risques à court terme d\'exploitation (voir note 28)', accounts: ['659'], side: 'SD' },
  ],
  '27A': [
    { label: 'Rémunérations directes versées au personnel', accounts: ['661', '662'], side: 'SD' },
    { label: 'Indemnités forfaitaires versées au personnel', accounts: ['663'], side: 'SD' },
    { label: 'Charges sociales', accounts: ['664'], side: 'SD' },
    { label: 'Rémunérations et charges sociales de l\'exploitant individuel', accounts: ['666'], side: 'SD' },
    { label: 'Rémunération transférée de personnel extérieur', accounts: ['667'], side: 'SD' },
    { label: 'Autres charges sociales', accounts: ['668'], side: 'SD' },
  ],
  '27B': [
    { label: 'TOTAL (1)', accounts: ['661', '662', '663', '664', '666'], side: 'SD' },
  ],
  '28': [
    { label: '4. Dépréciations des stocks', accounts: ['39'], side: 'SC' },
    { label: '5. Dépréciations actif circulant H.A.O.', accounts: ['4998'], side: 'SC' },
    { label: '6. Dépréciations fournisseurs', accounts: ['490'], side: 'SD' },
    { label: '7. Dépréciations clients', accounts: ['491'], side: 'SC' },
    { label: '8. Dépréciations autres créances', accounts: ['492', '493', '494', '495', '496', '497', '498'], side: 'SC' },
    { label: '9. Dépréciations titres de placement', accounts: ['590'], side: 'SC' },
    { label: '10. Dépréciations valeurs à encaisser', accounts: ['591'], side: 'SC' },
    { label: '11. Dépréciations disponibilité', accounts: ['592', '593', '594'], side: 'SC' },
    { label: '12. Dépréciations et provisions pour risques à court  termes exploitation', accounts: ['4991'], side: 'SC' },
    { label: '13. Dépréciations et provisions pour risques à court  termes à caractère financier', accounts: ['599', '4997'], side: 'SC' },
    { label: '1. Provisions réglementées', accounts: ['15'], side: 'SC' },
    { label: '2. Provisions financières pour risques et charges', accounts: ['191', '192', '193', '194', '195', '196', '197', '1981', '1984', '1988'], side: 'SC' },
    { label: '3. Dépréciation des immobilisations', accounts: ['29'], side: 'SC' },
  ],
  '29': [
    { label: 'Intérêts des emprunts', accounts: ['671'], side: 'SD' },
    { label: 'Intérêts dans loyers de location acquisition', accounts: ['672'], side: 'SD' },
    { label: 'Escomptes accordés', accounts: ['673'], side: 'SD' },
    { label: 'Autres intérêts', accounts: ['674'], side: 'SD' },
    { label: 'Escomptes des effets de commerce', accounts: ['675'], side: 'SD' },
    { label: 'Pertes de change', accounts: ['676'], side: 'SD' },
    { label: 'Pertes sur cessions de titres de placement', accounts: ['6771'], side: 'SD' },
    { label: 'Malis provenant d\'attribution gratuite d\'actions au personnel salarié et aux dirigeants', accounts: ['6772'], side: 'SD' },
    { label: 'Pertes sur risques financiers', accounts: ['6791', '6795'], side: 'SD' },
    { label: 'Charges pour dépréciations et provisions à court terme financières (voir note 28)', accounts: ['6798'], side: 'SD' },
    { label: 'Intérêts de prêts et de créances diverses', accounts: ['771'], side: 'SC' },
    { label: 'Revenus de participations', accounts: ['772'], side: 'SC' },
    { label: 'Escomptes obtenus', accounts: ['773'], side: 'SC' },
    { label: 'Revenus de placement', accounts: ['774'], side: 'SC' },
    { label: 'Intérêts dans loyers de location acquisition1', accounts: ['775'], side: 'SC' },
    { label: 'Gains de change', accounts: ['776'], side: 'SC' },
    { label: 'Gains sur cessions de titres de placement', accounts: ['777'], side: 'SC' },
    { label: 'Gains sur risques financiers', accounts: ['778'], side: 'SC' },
    { label: 'Reprises de charges pour dépréciations et provisions à court terme à caractère financier (voir note 28)', accounts: ['779'], side: 'SC' },
  ],
  '30': [
    { label: 'Charges H.A.O. constatées à détailler :', accounts: ['831', '833', '837'], side: 'SD' },
    { label: 'Pertes sur créances H.A.O.', accounts: ['834'], side: 'SD' },
    { label: 'Dons et libéralités accordés', accounts: ['835'], side: 'SD' },
    { label: 'Abandons de créances consentis', accounts: ['836'], side: 'SD' },
    { label: 'Charges provisionnées H.A.O.', accounts: ['839'], side: 'SD' },
    { label: 'Dotations hors activités ordinaires', accounts: ['85'], side: 'SD' },
    { label: 'Produits H.A.O. constatés à détailler :', accounts: ['841', '843', '844', '847'], side: 'SC' },
    { label: 'Dons et libéralités obtenus', accounts: ['845'], side: 'SC' },
    { label: 'Abandons de créances obtenus', accounts: ['846'], side: 'SC' },
    { label: 'Tranferts de charges H.A.O.', accounts: ['848'], side: 'SC' },
    { label: 'Reprises de charges pour dépréciation et provisions à court terme H.A.O.', accounts: ['849'], side: 'SC' },
    { label: 'Reprises hors activités ordinaires', accounts: ['86'], side: 'SC' },
    { label: 'Subventions d\'équilibre', accounts: ['88'], side: 'SC' },
    { label: 'Participation des travailleurs', accounts: ['87'], side: 'SD' },
    { label: 'Impôts sur le résultat', accounts: ['89'], side: 'SD' },
  ],
  '31': [
    { label: 'Chiffre d\'affaires hors taxes', accounts: ['701', '702', '703', '704', '705', '706', '707'], side: 'SC' },
    { label: 'Participation des travailleurs aux bénéfices', accounts: ['871', '872'], side: 'SD' },
    { label: 'Impôt sur le résultat', accounts: ['89'], side: 'SD' },
  ],
  '32': [
    { label: 'PRODUCTION DE L\'EXERCICE', accounts: ['36', '37'], side: 'SD' },
  ],
  '34': [
    { label: '+ Valeurs comptables des cessions courantes d\'immobilisation (comptes 654)', accounts: ['654'], side: 'SD' },
    { label: '- Produits des cessions courantes d\'immobilisation (comptes 754)', accounts: ['754'], side: 'SD' },
    { label: '+ Revenus financiers', accounts: ['771', '772', '772', '773', '774', '775'], side: 'SC' },
    { label: '+ Gains de change', accounts: ['776'], side: 'SC' },
    { label: '+ Transferts de charges financières', accounts: ['787'], side: 'SC' },
    { label: '+ Produits H.A.O.', accounts: ['841', '842', '843', '843', '845', '846', '847'], side: 'SC' },
    { label: '+ Transferts de charges H.A.O.', accounts: ['848'], side: 'SC' },
    { label: '- Frais financiers', accounts: ['671', '672', '673', '674', '675'], side: 'SD' },
    { label: '- Pertes de change', accounts: ['676'], side: 'SD' },
    { label: '- Charges H.A.O.', accounts: ['83'], side: 'SD' },
    { label: '- Participation', accounts: ['87'], side: 'SD' },
    { label: '- Impôts sur le résultat', accounts: ['89'], side: 'SD' },
    { label: '- Actif immobilisé (b)', accounts: ['211', '2181', '2191', '212', '213', '214', '2193', '215', '216', '217', '218', '2198', '22', '231', '232', '233', '237', '2391', '2393', '234', '235', '238', '2392', '2394', '2395', '2398', '241', '242', '243', '244', '246', '247', '249', '248', '245', '2495', '251', '252', '26', '27'], side: 'SD' },
    { label: 'Actif circulant d\'exploitation (b)', accounts: ['485', '488', '31', '32', '32', '33', '34', '35', '36', '37', '38', '409', '41', '412', '413', '414', '415', '416', '417', '418', '185', '42', '43', '44', '45', '46', '47'], side: 'SD' },
    { label: '- Passif circulant d\'exploitation (b)', accounts: ['481', '482', '484', '4998', '419', '401', '402', '403', '404', '405', '406', '407', '408', '42', '43', '44', '185', '45', '46', '471', '472', '473', '474', '475', '476', '477', '499', '599'], side: 'SC' },
    { label: 'Actif circulant H.AO. (b)', accounts: ['485', '488'], side: 'SD' },
    { label: '- Passif circulant H.A.O. (b)', accounts: ['481', '482', '484', '4998'], side: 'SC' },
    { label: 'Endettement financier brut (Dettes financières* + Trésorerie Passif)', accounts: ['16', '17', '564', '565', '52', '53', '54', '56', '57', '581', '582', '55'], side: 'SC' },
    { label: '- Trésorerie Actif', accounts: ['50', '51', '52', '53', '54', '56', '55', '57', '581', '582'], side: 'SD' },
  ],
  '3E': [
    { label: 'Montant de l\'écart incorporé au capital', accounts: ['106'], side: 'SC' },
  ],
};

/**
 * Retrouve une ligne de mapping pour une note donnée via une correspondance
 * insensible à la casse sur un fragment du libellé OHADA. Lève une erreur si
 * aucune ligne ne correspond (fail-fast en dev plutôt que somme silencieuse à 0).
 */
export function getMappingLine(noteCode: string, labelIncludes: string): MappingLine {
  const lines = ACCOUNT_MAPPING[noteCode] || [];
  const needle = labelIncludes.toLowerCase();
  const found = lines.find((l) => l.label.toLowerCase().includes(needle));
  if (!found) {
    throw new Error(
      `[account-mapping] Aucune ligne trouvée pour note "${noteCode}" avec libellé contenant "${labelIncludes}"`
    );
  }
  return found;
}

export function getMappingLines(noteCode: string): MappingLine[] {
  return ACCOUNT_MAPPING[noteCode] || [];
}
